---
services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2025.10.3
    container_name: authentik-proxy
    security_opt:
      - no-new-privileges:true
    # profiles: ["core", "all"]
    networks:
      - traefik
    environment:
      AUTHENTIK_HOST: ${AUTHENTIK_HOST}
      AUTHENTIK_TOKEN: ${AUTHENTIK_PROXY_TOKEN:-error}
      AUTHENTIK_INSECURE: ${AUTHENTIK_INSECURE:-false}
      AUTHENTIK_PROXY_LOG_LEVEL: ${AUTHENTIK_PROXY_LOG_LEVEL:-info}
    secrets:
      - authentik_proxy_token
    restart: always
