---
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2026.5.0
    profiles: ["dmz"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - TUNNEL_TOKEN_FILE=${CF_TUNNEL_TOKEN_FILE}
    networks:
      - traefik
    command: tunnel run
    secrets:
      - cloudflared_token
    restart: unless-stopped
