---
services:
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v2.4.1
    profiles: ["dmz"]
    environment:
      # - IMMICH_LOG_LEVEL=verbose
      - DB_HOSTNAME=immich-postgres
      - DB_DATABASE_NAME_FILE=${IMMICH_POSTGRES_DB_FILE-/run/secrets/immich_postgres_db}
      - DB_USERNAME_FILE=${IMMICH_POSTGRES_USER_FILE-/run/secrets/immich_postgres_user}
      - DB_PASSWORD_FILE=${IMMICH_POSTGRES_PASS_FILE-/run/secrets/immich_postgres_password}
      - REDIS_HOSTNAME=immich-redis
      - IMMICH_TELEMETRY_INCLUDE=${IMMICH_TELEMETRY_INCLUDE:-all}
    networks:
      - traefik
      - db
    volumes:
      - ${IMMICH_FOLDER}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich-postgres
      - immich-redis
    restart: always
    secrets:
      - immich_postgres_db
      - immich_postgres_user
      - immich_postgres_password
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.${FQDN}`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.http.routers.immich.middlewares=chain-no-auth@file

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    profiles: ["dmz"]
    security_opt:
      - no-new-privileges:true
    environment:
      - PORT=3003
      - ML_MODEL_PATH=/models
    volumes:
      - model-cache:/cache
    networks:
      - db
    restart: always
    healthcheck:
      disable: false

  immich-postgres:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:17-vectorchord0.4.3-pgvectors0.3.0
    shm_size: 128mb
    profiles: ["dmz"]
    environment:
      - POSTGRES_DB_FILE=${IMMICH_POSTGRES_DB_FILE:-/run/secrets/immich_postgres_db}
      - POSTGRES_USER_FILE=${IMMICH_POSTGRES_USER_FILE:-/run/secrets/immich_postgres_user}
      - POSTGRES_PASSWORD_FILE=${IMMICH_POSTGRES_PASS_FILE:-/run/secrets/immich_postgres_password}
      - TZ=${TZ:-UTC}
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - DB_STORAGE_TYPE=${IMMICH_DB_STORAGE_TYPE:-SSD}
    networks:
      - db
    volumes:
      - immich-db:/var/lib/postgresql/data
    secrets:
      - immich_postgres_db
      - immich_postgres_user
      - immich_postgres_password
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$(cat /run/secrets/immich_postgres_user)" -d "$(cat /run/secrets/immich_postgres_db)"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  immich-redis:
    container_name: immich-redis
    profiles: ["dmz"]
    image: redis:alpine
    networks:
      - db
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

networks:
  db:

volumes:
  immich-db:
    name: immich-db
    driver: local
  model-cache:
    name: immich-model-cache
    driver: local
