# yamllint disable rule:line-length
---
services:
  nextcloud:
    image: linuxserver/nextcloud:33.0.2
    container_name: nextcloud
    profiles: ["dmz"]
    networks:
      - traefik
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud-config:/config:rw
      - nextcloud-data:/data:rw
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_postgres_db
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_postgres_password
      - NEXTCLOUD_URL=https://${FQDN}
      - JWT_SECRET_KEY=${NEXTCLOUD_JWT_SECRET_KEY}
    restart: unless-stopped
    depends_on:
      nextcloud-db:
        condition: service_healthy
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - nextcloud_postgres_db
      - nextcloud_postgres_password
      - nextcloud_postgres_user
    labels:
      - traefik.enable=true
      # HTTP Routers
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${FQDN}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.service=nextcloud
      # HTTP Services
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      # Middlewares
      # - traefik.http.routers.nextcloud.middlewares=chain-oauth@file
      - traefik.http.routers.nextcloud.middlewares=nextcloud@docker
      - traefik.http.middlewares.nextcloud.chain.middlewares=headers,redirectregex
      # - traefik.http.middlewares.headers.headers.customRequestHeaders.X-Forwarded-Proto=https
      # - traefik.http.middlewares.headers.headers.customRequestHeaders.X-Forwarded-Host=nextcloud.${FQDN}
      # - traefik.http.middlewares.headers.headers.customRequestHeaders.X-Forwarded-Port=443
      # - traefik.http.middlewares.headers.headers.customResponseHeaders.X-Accel-Buffering=no
      - traefik.http.middlewares.headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload
      - traefik.http.middlewares.redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav
      - traefik.http.middlewares.redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav

  nextcloud-db:
    image: postgres:18-alpine
    container_name: nextcloud-db
    profiles: ["dmz"]
    environment:
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_postgres_db
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_postgres_password
    networks:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud-db:/var/lib/postgresql/data
    restart: unless-stopped
    secrets:
      - nextcloud_postgres_db
      - nextcloud_postgres_user
      - nextcloud_postgres_password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$(cat /run/secrets/nextcloud_postgres_user)" -d "$(cat /run/secrets/nextcloud_postgres_db)"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  db:

volumes:
  nextcloud-config:
    name: nextcloud-config
    driver: local
  nextcloud-db:
    name: nextcloud-db
    driver: local
  nextcloud-data:
    name: nextcloud-data
    driver: local
    driver_opts:
      type: none
      device: "/mnt/nfs/nextcloud/data"
      o: bind
