---
name: cadvisor
services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    security_opt:
      - no-new-privileges:true
    profiles: ["prod", "dmz"]
    networks:
      - traefik
    # devices:
    #   - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      "--housekeeping_interval=5s"
    restart: unless-stopped

