---
# defaults file for ubuntu-host-setup
provision_sudo_user: false
generate_motd: false
disable_root_ssh: false
ssh_allowed_users:
  - "{{ sudo_user }}"
install_qemu_guest_agent: false
lxc_reboot_wait_delay: 5
lxc_reboot_wait_timeout: 60
lxc_reboot_check_command_delay: 1
lxc_reboot_check_command_retries: 60