smtp:
  domain: mail.${FQDN}
  listen: 0.0.0.0:8025

configs:
  # Mailrise shall act as a relay to the Apprise container
  notify_all:
    urls:
      - apprise://apprise:8000/
    mailrise:
      title_template: "$subject"
      body_template: "**From:** $from\n**Body:**\n$body"
      body_format: markdown
