---
services:
  authentik-ldap:
    image: ghcr.io/goauthentik/ldap:2025.12.1
    container_name: authentik-ldap
    security_opt:
      - no-new-privileges:true
    profiles: ["prod", "dmz"]
    networks:
      - traefik
    environment:
      AUTHENTIK_HOST: ${AUTHENTIK_HOST}
      AUTHENTIK_TOKEN: ${AUTHENTIK_LDAP_TOKEN:-error}
      AUTHENTIK_INSECURE: ${AUTHENTIK_INSECURE:-false}
      AUTHENTIK_LDAP_LOG_LEVEL: ${AUTHENTIK_LDAP_LOG_LEVEL:-info}
    secrets:
      - authentik_ldap_token
    restart: always
