http:
  routers:
    authentik-public:
      rule: Host(`auth.{{env "DOMAIN"}}`)
      entryPoints:
        - websecure
      middlewares:
        - chain-authentik-public
      service: authentik-public
      tls:
        certResolver: cloudflare

  services:
    authentik-public:
      loadBalancer:
        passHostHeader: false
        serversTransport: authentik-transport
        servers:
          - url: https://authentik.local.{{env "DOMAIN"}}/

    blocked:
      loadBalancer:
        servers:
          - url: http://0.0.0.0

  serversTransports:
    authentik-transport:
      serverName: authentik.local.{{env "DOMAIN"}}

  middlewares:
    cf-real-ip:
      headers:
        customRequestHeaders:
          X-Forwarded-For: { headers.CF-Connecting-IP }

    authentik-public-headers:
      headers:
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        customRequestHeaders:
          # Backend (prod Authentik) expects this Host
          Host: authentik.local.{{env "DOMAIN"}}
          # But client should keep seeing this Host
          X-Forwarded-Host: auth.{{env "DOMAIN"}}
          X-Forwarded-Proto: https
          X-Forwarded-Port: 443

    authentik-rewrite-headers:
      headers:
        customResponseHeaders:
          Location: https://auth.{{env "DOMAIN"}}

    authentik-public-rewrite-location:
      redirectRegex:
        regex: ^https://authentik\.local\.{{env "DOMAIN"}}(/.*)?$
        replacement: https://auth.{{env "DOMAIN"}}$1
        permanent: false

    authentik-public-block-admin:
      errors:
        status:
          - 403
        service: blocked
        query: /

    chain-authentik-public:
      chain:
        middlewares:
          - cf-real-ip
          - authentik-public-block-admin
          - authentik-public-headers
          # - authentik-public-rewrite-headers
          - authentik-public-rewrite-location
