---
http:
  routers:
    authentik-public:
      rule: Host(`auth.{{env "DOMAIN"}}`)
      entryPoints:
        - websecure
      middlewares:
        - chain-authentik-public
      service: authentik-public
      tls:
        certResolver: cloudflare

  services:
    authentik-public:
      loadBalancer:
        passHostHeader: false
        serversTransport: authentik-transport
        servers:
          - url: https://authentik.local.{{env "DOMAIN"}}/

  serversTransports:
    authentik-transport:
      serverName: authentik.local.{{env "DOMAIN"}}

  middlewares:
    authentik-rewrite-headers:
      headers:
        customResponseHeaders:
          Location: https://auth.{{env "DOMAIN"}}

    authentik-public-block-admin:
      errors:
        status:
          - 403
        service: noop@internal
        query: /

    authentik-public-rewrite-location:
      redirectRegex:
        regex: ^https://authentik\.local\.{{env "DOMAIN"}}(/.*)?$
        replacement: https://auth.{{env "DOMAIN"}}$1
        permanent: false

    chain-authentik-public:
      chain:
        middlewares:
          - authentik-public-block-admin
          - authentik-public-rewrite-location
