tcp:
  routers:
    portainer-agent:
      entryPoints:
        - portainer-tcp
      rule: "HostSNI(`phobos.{{env "DOMAIN"}}`)"
      service: portainer-agent
      tls:
        passthrough: true
  services:
    portainer-agent:
      loadBalancer:
        servers:
          - address: portainer-agent:9001