tcp:
  routers:
    komodo-periphery:
      entryPoints:
        - komodo-tcp
      rule: "HostSNI(`phobos.{{env "DOMAIN"}}`)"
      service: komodo-periphery
      middlewares:
        - private-ips-tcp@file
      tls:
        passthrough: true
  services:
    komodo-periphery:
      loadBalancer:
        servers:
          - address: komodo-periphery:8120
