---
tcp:
  routers:
    portainer-agent:
      entryPoints:
        - portainer-tcp
      rule: HostSNI(`phobos.{{env "DOMAIN"}}`)
      service: portainer-agent
      middlewares:
        - private-ips-tcp@file
      tls:
        passthrough: true
  services:
    portainer-agent:
      loadBalancer:
        servers:
          - address: portainer-agent:9001
