---
# Traefik 3.x (YAML)

################################################################
# Global configuration - https://doc.traefik.io/traefik/reference/static-configuration/file/
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# API and Dashboard
################################################################
api:
  dashboard: true
  insecure: false # Change to false in production
  debug: true

################################################################
# Entrypoints - https://doc.traefik.io/traefik/routing/entrypoints/
################################################################
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    http3: true
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        # Local IPs
        - 127.0.0.1/32
        - 192.168.1.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        # Cloudflare IPv4 IP ranges
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        # Cloudflare IPv6 IP ranges
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: integraceion.com
            sans: "*.integraceion.com"
    http3: true
    transport:
      respondingTimeouts:
        readTimeout: 0s # for big file uploads
        idleTimeout: 0s
        writeTimeout: 0s

################################################################
# Let's Encrypt (ACME)
################################################################
certificatesResolvers:
  cloudflare:
    acme:
      email: integraceion@gmail.com
      storage: /var/traefik/certs/acme.json
      # Default CA server is Let's Encrypt production server, uncomment the next line to use staging server
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        # delayBeforeCheck: 30 # (Seconds) Default is 120
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

serversTransport:
  insecureSkipVerify: false # Set to true on individual middlewares for services that include self-signed certs

################################################################
# Providers - https://doc.traefik.io/traefik/providers/docker/
################################################################
providers:
  docker:
    exposedByDefault: false
    network: traefik
    endpoint: tcp://socket-proxy:2375
  file:
    directory: /etc/traefik
    watch: true

################################################################
# Logs - https://doc.traefik.io/traefik/observability/logs/
################################################################
log:
  level: ERROR # Options: DEBUG, PANIC, FATAL, ERROR (Default), WARN, and INFO
  filePath: /logs/traefik.log
  # format: json
  noColor: false # Best for txt logging format which is the default
  maxSize: 100 # Maximum size of the log file in MB
  compress: true # Compress the log file when it reaches the maximum size

################################################################
# Access logs - https://doc.traefik.io/traefik/observability/access-logs/
################################################################
accesslog:
  addInternals: true
  filePath: /logs/access.log
  bufferingSize: 100
  fields:
    names:
      StartUTC: drop # Write logs in Container Local Time instead of UTC
  filters:
    statusCodes: "200-299,400-499,500-599"

################################################################
# Prometheus Metrics - https://doc.traefik.io/traefik/observability/metrics/prometheus/
################################################################
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

################################################################
# Experimental Features & Plugins - https://doc.traefik.io/traefik/reference/static-configuration/file/#experimental
################################################################
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.5"
