http:
  middlewares:
    chain-authentik:
      chain:
        middlewares:
          #- traefik-bouncer # leave this out if you are not using CrowdSec        
          - rate-limit
          - secure-headers
          - compress
          - authentik
