http:
  middlewares:
    chain-authentik:
      chain:
        middlewares:
          - crowdsec # Comment out if not using CrowdSec
          - rate-limit
          - secure-headers
          - compress
          - authentik
