http:
  middlewares:
    chain-oauth:
      chain:
        middlewares:
          - crowdsec # Comment out if not using CrowdSec
          - rate-limit
          - secure-headers
          - compress
          - oauth
