http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          #- traefik-bouncer # leave this out if you are not using CrowdSec
          - rate-limit
          - secure-headers
