---
http:
  middlewares:
    chain-basic-auth:
      chain:
        middlewares:
          - crowdsec # Comment out if not using CrowdSec
          - rate-limit
          - secure-headers
          - basic-auth
