---
services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: linuxserver/socket-proxy:3.2.15
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["dmz"]
    networks:
      socket_proxy:
    privileged: true # true for VM. False for unprivileged LXC container.
    ports:
      - "127.0.0.1:2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ### Security critical - Revoked by Default
      - AUTH=0
      - SECRETS=1 # Required to read Docker secrets (Komodo, Portainer)
      - POST=1 # Required to start/stop/create containers (Komodo)
      # Not always needed
      - BUILD=0 # Required if using "Build" features in Komodo
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Required to list and manage containers (Traefik, Komodo, Portainer, etc.)
      - DISTRIBUTION=0
      - EXEC=1 # Required to use the "Terminal" in Komodo UI
      - IMAGES=1 # Required to pull new versions from Renovate updates (Komodo, Portainer)
      - INFO=1 # Required to correctly determine container and stack state (Komodo, Portainer)
      - NETWORKS=1 # Required to attach containers to Traefik/DB networks (Komodo, Portainer)
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Required for service routing and communication among containers (Komodo, Portainer)
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Required to manage resource allocation and scaling of the services (Komodo, Portainer)
      - VOLUMES=1 # Required for persistent storage (Komodo, Portainer)
    read_only: true
    tmpfs:
      - /run
