#ENC[AES256_GCM,data:1Wsiy9mRVwRr0Hmn8f8BpX4ZaQ==,iv:9MpcBCf9Dws+RjaqGeDDzqh0DcYVlnbngGBe3gx5RxM=,tag:qJjdUjUtBY5y0SOJckPK+Q==,type:comment]
#ENC[AES256_GCM,data:AMDXMsjPiFXL+gFXg4MWsgRPvh0t66nxNnWDnfRUelYGpGgV/4/EQw/QU8JASNEBhGcPjBZHyKN21cP5DAj/,iv:IVLx+XrWCNKfAuIvYj7Gf0mGmcujX3ND0A1T2HJR/mg=,tag:Qx736UYBH7xe6d4CrQwVWg==,type:comment]
#ENC[AES256_GCM,data:Fo+VaVxKjvyYy6RSqkR/li7Zo9pfWZFjAmSj/0556kFq0d63vH+IEgbL4ZWKNam2lsTQojfkedp807D1uL5igtDMAb6x5ZSwE4HaP9RQD+UIboQZr+fjOWFuJQ==,iv:piyAkBVoNrkuLCITur1TXmJIdg8nFD8PX+Y35Rc9sU4=,tag:38AS57ZAVIMp0vzgKHsKJQ==,type:comment]
#ENC[AES256_GCM,data:88ofaJNFiWb7zKAzmXV1V57f1XQ0u7k4T5uq8aqOQKBdZNWIQQ6tdkc9sjdWkJyLEtmJm3/lTppk2/WmK0BO,iv:AiySNgrxgVzN1MqnmqZlE9+Ynmn34QQ5J8/uKZv9JBA=,tag:4bmpWvqTEJb3DVP63UMpGw==,type:comment]
global:
  checkNewVersion: ENC[AES256_GCM,data:Nn0OZw==,iv:nSPdPRbLQoMOMGQ7wMS9bhd7mrUL9YROxkCBXdhCXB8=,tag:fPzz4f26ifXi8zSq7DZmxw==,type:bool]
  sendAnonymousUsage: ENC[AES256_GCM,data:Zm2an4w=,iv:6d3+uUcNuvbo8fpm6hsvlc0Da4f+CokwnTxikD/7WRk=,tag:2MiCfyoBScs20NJOQ7W1tA==,type:bool]
#ENC[AES256_GCM,data:y6AiudJ1S6F86DdDE+Mr9gInx+cg6Tu5hhrgomxoR0IixHS4BqHGc17xqOiXcac6lbihEq8Qc/vaepqSkT2P,iv:ZMkxsiWXvaxghsRZ3OSsNgoeCe+EyKEaXweeqLZk08Q=,tag:8fPSjmyGq+r9zk2WqyDn7Q==,type:comment]
#ENC[AES256_GCM,data:KOXjty2ZAhPSrGDHNioNe8V/,iv:n7BeRsu9wbW9mdMSmG4vjICPN/Su7BVKg36QngujhXo=,tag:Kc8N+R0NdbhJLuDzUkL+vg==,type:comment]
#ENC[AES256_GCM,data:cdbwmIKKPS6pk1i/Be2vv3VDoIzbcEt28tWwbYJcdUj5cHtaJipmVXJGB3U6LdKKcRZK2shk/l9u2GUjavl2,iv:naUZ+o+0BZrBZXSNFacpBZOCeSsJuXzSEyoGm2eiudE=,tag:hxA7hr92BxIe4IlJoOZE0A==,type:comment]
api:
  dashboard: ENC[AES256_GCM,data:8xBJgA==,iv:Atxu7s25yAkGvkfxQTbCGxxDiM2XZe8X4nPhD1bxHW8=,tag:VLL28BVV0IRo6tfa22waog==,type:bool]
  #ENC[AES256_GCM,data:e50V900k3+nj+Kg0ozoT/Ty/PPgxTrEnPjqbSqBm,iv:m1q57SXqUQ54Z+YOw8tD1nS4OoyZcdKScA6/DCzr/q4=,tag:ucfGVJEe+f1kcbwlnynxeQ==,type:comment]
  insecure: ENC[AES256_GCM,data:SVv+HJQ=,iv:eMjfNl3OOI7O2Z+/5vG7KYzL0xWnmJ9HHTfvXeS3mak=,tag:KXUrGtv3hERjeAjpTQhYLg==,type:bool]
  debug: ENC[AES256_GCM,data:D11ncQ==,iv:C8riHZU1nUwOxlpTsn/7I04LpaBwzqVkdDpPiYRAVXw=,tag:lcWSQZ5r4tQwlPOvfbcrPQ==,type:bool]
#ENC[AES256_GCM,data:pT3Nl94C7eatIMuBOt27ii8E/mtUChjgtIcQpKPA6umnp+EniqVKjAjHAs6yKggl2kMbvL5g8vv2r30EBxAn,iv:F2a8sV/dF9xUI9eDAXMTySpvNBHmSOLC4k+n2SbwoPA=,tag:24yOeNw9gA8eHL6OnHauRA==,type:comment]
#ENC[AES256_GCM,data:LVhI4Vg0ZA2e30Obt/NhNy2AP27PPUt0P/OG3Mk/O9maJJ6P4nQY74vCjEfIlWyY3xopmre6VR403CkTGn7E1CTm,iv:wOihxdkblX6MfuyBlcZbMO9xxZRuuKvsVSS4zO+EqEE=,tag:nsNhc89aZqxkBJ3Mp/5RWQ==,type:comment]
#ENC[AES256_GCM,data:P9LiL0YpW7TmGzmTh943RySRctMwARc6wHQclUTAccpbvi0cTKMc2PWeLvsA4bld36zyVCwsa3i39pqG+WnC,iv:1NC3GiMzlHnsMaafC8K6CJRrc18CQn9f6cBjZlADN5I=,tag:9aFf95t2YmE1MeoUb7o0Qw==,type:comment]
entryPoints:
  web:
    address: ENC[AES256_GCM,data:IUu9,iv:IFXV4Iho7WkAmiMSKZaqU7DwVirSeWoeCZovcjceBr8=,tag:xlCmaF7NzMj8mGin9cYXBw==,type:str]
    http:
      redirections:
        entryPoint:
          to: ENC[AES256_GCM,data:kTsYbILPrgMa,iv:qfs0Lx6aRf9n9CCB+yaPnxMzlyALdjoWrDGWlGRoock=,tag:LRGZlP85pM0EJSCVszP2vw==,type:str]
          scheme: ENC[AES256_GCM,data:IR9nzko=,iv:bmbeB0WasUmnDBWUkRwO7duY2afJsPMjRsxLfAQB5QM=,tag:cU+m5tys85GXWNgX+u+BRQ==,type:str]
          permanent: ENC[AES256_GCM,data:rrr1Nw==,iv:SdyXA8nKHb47Ufx+8rMBK9ioYvDdgYr7gQmGNoWeyo0=,tag:KBRqkJTaApSm+A+tgDLAnA==,type:bool]
    http3: ENC[AES256_GCM,data:JuhgdA==,iv:RM0cKgys7Qw0c1s/zChYNmyg841AEP79z9zgNK2W4i8=,tag:bVLcw2euNufU27N/ZrBSpw==,type:bool]
  websecure:
    address: ENC[AES256_GCM,data:DKUSsA==,iv:KwQdXxiQ2GEUuXXY/bMac4ApBIxzdO/o5tlt3WGArLs=,tag:JGfNYK+MVsHNjjl180FUdw==,type:str]
    forwardedHeaders:
      trustedIPs:
        - ENC[AES256_GCM,data:GbvnMVkbmhkmoA==,iv:j0NMbpkH0tO7RUFPZTvAJ3TubaW+4y4j2KhYsCtsReg=,tag:NJsnGl0TBlYTDvm3e8oA4g==,type:comment]
        - ENC[AES256_GCM,data:EpIpfHhGRPCXUVPR,iv:mY/ALDiQk2xbIbbEdukdTO2c5OCO9px5KDcOMoS/QMc=,tag:fnesazCSTc9dyvyJHmHutA==,type:str]
        - ENC[AES256_GCM,data:ZgiF2ilBloiiyKstWjs=,iv:HwBw1dD/9bBF4O4CaQzYt25s7tzrvYlxZV6lqinADPs=,tag:aH/qEPKBDzRH/6x7UFsrLg==,type:str]
        - ENC[AES256_GCM,data:hw3FyEHJyr3jC5UC2A==,iv:yE79NayP9ZO5My0z+RanVZ74LtcVXRhVpqg+mzO6jyE=,tag:Woivku88CngcdioqYhwetg==,type:str]
        - ENC[AES256_GCM,data:cA0NpqpqtkUCdQ==,iv:Bw70vxHcXX3b/ErOnDqw/lOP765tYaJsBPsQc725XFE=,tag:G2A8qiKwt8zB92rpWv1m/w==,type:str]
    http:
      tls:
        certResolver: ENC[AES256_GCM,data:x4+RlJh9fCo4Gg==,iv:3zhZ1tE1Gy6xq0KKHQ2Pqo8Zk+Hd49ps3NIaVOzis6s=,tag:Qa+6j6dnWAGsPW1/Dw6qVw==,type:str]
        domains:
          - main: ENC[AES256_GCM,data:FGrz6IV74vA9+uNj9wnc+n9fs885hw==,iv:rnI7ouHE9XIg17qXODEzj4/UYV0hdvWZCJ7DIwpnIuU=,tag:RoOjZvllP0mxLdMe9ekluQ==,type:str]
            sans: ENC[AES256_GCM,data:oaSg7hsJW+G+AhBDZT5zy7GRiFEGoQmm,iv:bmtUIASDLIIAk3sdhhaEEf30vy1ar2MVor7ZZAMgH/c=,tag:bHDp9YGLL1U9fRHn0LNyNw==,type:str]
    http3: ENC[AES256_GCM,data:bTknDw==,iv:WjFELb2x7uozcGd5talzRqRhfpk0U5C5XPepjI57lDQ=,tag:ux9XoYOheTxfQsX4Oyqp7w==,type:bool]
  smtpsecure:
    address: ENC[AES256_GCM,data:26b7sA==,iv:I7mcIkIxiU88bu3+P+1ehWhWq9CrvgHDfycZlb/hM6E=,tag:DN165z8WeefEktDRtKjSig==,type:str]
  graphite-tcp:
    address: ENC[AES256_GCM,data:LjDraxoSvhQD,iv:Hm3PxCLnSraIfzqDT0GXlfsjT1ZVvVeG5ch2AZ3PMvg=,tag:wytCSrXMNUQvVO/THLcT0w==,type:str]
  graphite-udp:
    address: ENC[AES256_GCM,data:Rrv2HyBnSh/G,iv:CS9pUoeKg92RyhsunMQx6jAzj2+Gt6I/iytuX94wV5o=,tag:KS//JcENYyGOIg6IW+sLyQ==,type:str]
#ENC[AES256_GCM,data:mSpp0DOhX/J9oYHlWYO5IQl+nNQvHpl9zrO18JR3EYg4E5SsoXKlRoy/EUcFyJH4RNlG0jC1y2dvnN1sduG1,iv:hDZgbVeO/STChxthX+EpK/Cb8OGqfqnb87KndUMEd3A=,tag:E1XKoHcDitpvs+bC1pq+Tw==,type:comment]
#ENC[AES256_GCM,data:HyvmEmqCKH6B4a7PS166Cjmy6h4d,iv:WAlyMhy8eWwcILnjWo/qmkiJ3pc5pit1WDVGKTtxixY=,tag:obMFCpJ/3TI0T9jZ1hE6Bg==,type:comment]
#ENC[AES256_GCM,data:+7meqDkVg7QxXjEu2WaZQrJ+zz6IfB9WlbYmOU5UhZ0IVToeqGPyrGVvyqLMbNyYfpyAxF7o3DW6iZ4AF23v,iv:kDsJIv9aUvzWcmLpuWn6ddcXEjPcMiyZtFHflPBHY4E=,tag:PSAe3Z3xpqxSF016RS2PMA==,type:comment]
certificatesResolvers:
  cloudflare:
    acme:
      email: ENC[AES256_GCM,data:HGdfD9P9NbANSsUoMguBbTyfd/IYzg==,iv:DGO5hVU36At4EpVS41NM/n+Rnx+i4IUrWt12dtgd/yk=,tag:fp9Xijo4TxfwFx9aMgg1Mw==,type:str]
      storage: ENC[AES256_GCM,data:0d18TwyBuU4oXJO1wL6rBPOR+IZiUgbGqMkUww==,iv:ztwkmR8bgkk931H8UetuwL+EpsZ2PtKRWrRPImmlyCg=,tag:snIj9g0ObruAUtMMXIQeYg==,type:str]
      #ENC[AES256_GCM,data:QGDMmMCdC+kAULMZJWS9pzO6oVrnLiMDy/7Zuu19GUvSfuIJs3TmkejbwfJKe+nU9CjQQRjRqD/WJTUgoNIerCDnBgS91M6M/lDSAeawI5qLrgb3pm2q8No3hObG6RtmPwNklQ==,iv:zuXjKVf4S4AbLnJ6XtCbM0JyTzL+0aolZab57ilH6TA=,tag:bXLYtlGgnFpNPkfL4K6Ohg==,type:comment]
      #ENC[AES256_GCM,data:j3iNAnb+t/8qXwCXflCbZxHqwkL1SgYniat4Oa/F/KfOzMbd5gLL2moANSujxs9kY9FI8NHcChRyaTxCPG+jDROJWw==,iv:jWvfHVtPziO6tHc7IsnH50Y1Dacf8s4bkvIlr5cz8BY=,tag:8KbXvNvx/PlHrbklO5YLIA==,type:comment]
      dnsChallenge:
        provider: ENC[AES256_GCM,data:XFaX3LgpLapLyw==,iv:gEVz3DGysjFwcBdOwjAOQxleCvxBEDVlC99tdgZ6HF8=,tag:k5fWMwulGL5vS5LMJgjBUQ==,type:str]
        #ENC[AES256_GCM,data:nSy6LvJotoyVQa/KWTE8glZ2i7r2JMMvjeDEnY6qujI3dbRoqvkXdvPyfo6l+1D4,iv:y3BQV4OFHu49dALiwrM7CkHGriXL2trK9it0PHt2Tec=,tag:7C6XjgVll1j2jIqnGqUEIQ==,type:comment]
        resolvers:
          - ENC[AES256_GCM,data:BPJy3n+co3O1Kg==,iv:1R6aMM//ah1xhFtQHgslEmd87J7rOsqgwdMsogmBjcc=,tag:ygyVfLW7KZhRuvPRUMmILA==,type:str]
          - ENC[AES256_GCM,data:hKFfVl8FK0BHCw==,iv:SPP/jrSeT7BryxsvbDdgaCF5s/pbe6xVOrqKBHbUzno=,tag:33QZm/hLHLMwOYuSbtU4tQ==,type:str]
serversTransport:
  #ENC[AES256_GCM,data:E0gMvuyNalJPnGO/UgA+zaLRht8gNoK/z/OsGaMaPha8SvFqrVleHLOD1o5vWs4N+Oie55dWyhTj8E3rjFWfgLT2N3BzjOtM3Ow+AO3tA81RFQ==,iv:c4dgqTUWM7tnYCo0df4ZyryshqiDwr54uYQnblV/vF0=,tag:7okceJM1DsEVflC7iXQZ6w==,type:comment]
  insecureSkipVerify: ENC[AES256_GCM,data:XBvi0xM=,iv:O8yc9psHC8j6OCgOkipgeZP/AwvOAtIiddgHxSO6MfY=,tag:TuPBeTA78tkOMAfqSFAp3Q==,type:bool]
#ENC[AES256_GCM,data:ER8XFOvjouhh7aaMKALEz04yPIKT5aqEVEXS9SmCMWmP9UgPiiATFPES5BO9Y8bXI7elY5BDwXhw1zc9s7O4,iv:G1orSGEMn+70oVXdpViGuKS5nhhc0E3FPzelewIPr+c=,tag:SKFL+SDDAdR50ndTN6gVFQ==,type:comment]
#ENC[AES256_GCM,data:CFIVFC+PvMjRbY+X7t8OkdhK3g6hAplTl70Wy398+1RcP6wblZHnl1SQ1NdVSGCIY2y6/Q3VjHQnfUNvwA==,iv:Ivfj5yC0F88Z1zWSCoSqG6tPGemZNst1fuFMKcfHrCQ=,tag:15yvcqTcJZ8QV0sv7tWr8Q==,type:comment]
#ENC[AES256_GCM,data:+phKoTMCN/th09YEMzCWI6m0Wxoso/fLOBg4/ts4MIjUqi2ejEon36Jy5HJt9cwezKze2qhCcdfh5HqucSQD,iv:EjP2ZCLMSCp55mowZ821bE6HSF7jAy6CXE5eDk8zAIk=,tag:trS8jcsg1oRekPXsQpFlbg==,type:comment]
providers:
  docker:
    exposedByDefault: ENC[AES256_GCM,data:E2ht9pU=,iv:TS/cEjPXQ3GRhJQfKxJJIV+nwl22/ZC1UBrv+xgRAGc=,tag:1TM/f8rfttBdmjJteJSPDw==,type:bool]
    network: ENC[AES256_GCM,data:MzE6BiInUg==,iv:NzljBqrxuUljcVueN3+n+LVi3RKr378ZBdZdUkxDBmg=,tag:f2EFF48zTGvaiK/PCziBzw==,type:str]
    endpoint: ENC[AES256_GCM,data:432p5S1hH4AU45zPZbRtofskWPJedbw=,iv:3aMqej13bZ56YMUwd5v2pf5pzmb4o0RhblIKgrSvLMs=,tag:euhO0vluGz3W1ydcTeUcFg==,type:str]
  file:
    directory: ENC[AES256_GCM,data:FODBWlPZdMbGyKoc,iv:br4e8dRZRPbWAYrLfjo3RNrN/9rFCJJK58UDZpR7wrY=,tag:VDVoqsy9sYiWtQNCNpAE6w==,type:str]
    watch: ENC[AES256_GCM,data:6KisoQ==,iv:HI92xnnW3YbezIIr2M8AtX3Tobk83mG17E84DPGk5nI=,tag:BJ2kRJ1gTSD8Sn/8yWMZaw==,type:bool]
#ENC[AES256_GCM,data:jn0slD6fby1aCaBaQnUlBtvbxGibRfm/3rHy6O4lwp4uDWau/CckxhoyPt/1R/P4WNu9FWyBBlRa9iLUCkrd,iv:uNticiRhA41AwxmQ5p5/kFxysxS5Dxqm64kyy3zx5wU=,tag:KFwOY57t4+bx3KmOA8jHNA==,type:comment]
#ENC[AES256_GCM,data:bK7l9gxLAG0PhesD9QTP8SSwO4KfnpB6NkN+MwRbEgOihXMG4kamTZIX+RgQv5jEtbTBiuNVwwmpFA==,iv:UJv/eHB3mfuydUZAji9kc35kiLw16dlTTNhTBZxZunM=,tag:Z2tqOzCdeRiHUr5Pu8oDkw==,type:comment]
#ENC[AES256_GCM,data:dFX6yo29tq6hjsIEYnMic5azUjJundV02Zs7hlBIwqDhnpQLvMNq8RE/WJmvgfvVXQ+dnKFfkzdNoqKE7NuB,iv:9i3ImhTkkzFbYzg3F7zThVDN4uQf9YW0RuA8aJ4jAnk=,tag:nAYlXCgRfQw7DbwcUg+SdA==,type:comment]
log:
  #ENC[AES256_GCM,data:iH4iMGcQd3DG6chph/YzU0PXFKaexDh0ftow2HyZMomTI9aaqq6dcoHS17MK5yBIwlvrHfLFI6n3CinCKxs=,iv:ox5YYM2tLGq+t2dLv5or14dU0G6InL2FWSR8J3k/+Qw=,tag:vdC9Q5rrLZcaCbTOAEOtdg==,type:comment]
  level: ENC[AES256_GCM,data:1+BLwrc=,iv:p/3GsDX1QqMoX0FTY5U19IbyBLk9HjqSXdAJWe9QJEk=,tag:SGrjc+M2Rh7Bux6kYvYkiA==,type:str]
  filePath: ENC[AES256_GCM,data:JaREK7xLwOBuZpyGfRAL+O0=,iv:yzzPN6LwMZxxymy5HxgxUbvuztN85bMkZuiFCBe91ws=,tag:IIAvF1G1Cxv65qd5E31KZg==,type:str]
  #ENC[AES256_GCM,data:kO7sjjSwU3lMhs7RHA==,iv:vZlH0ILLqh2Z6Tn4VNVWz6M1ZwGa9rG3g4v1VL1YcwE=,tag:svFkAgmMBIx5yl3wmoh9QA==,type:comment]
  #ENC[AES256_GCM,data:kTIwKylYgmaY44e0lAkbSWWBoWAj+nchhHqT5FjIbEueQy2hdxDSYXzpfZynAOTdVw==,iv:JksbPV95gU09vmW22uHgMvy4/Dgvlzjyh+U2x68pjIo=,tag:QfuMUjOjvqMzTCUF2FGgLg==,type:comment]
  noColor: ENC[AES256_GCM,data:lDqryzc=,iv:bVv8BguNpacmcuHyN3URm2qWhoNtYvCxgYdXMOPoFjA=,tag:KaQouy9DRAVx/LU9xuxICw==,type:bool]
  #ENC[AES256_GCM,data:XRdBTE/+toDq7dDq2HGsxLi3a+h9Iu0taqyWUkTuy7NXcqw=,iv:R3yJDxHsTuZkyC6PaprHKbMvTQqGg6gdeJRB7uBSckE=,tag:RILb5+FMIhELDcre6rz4NQ==,type:comment]
  maxSize: ENC[AES256_GCM,data:HBQq,iv:LlQcq3I01xM2BIYcW/SvgJWQAbKOddb+4AA2+iUqb54=,tag:KGqP7iuxiDK5q8+vDIc9NQ==,type:int]
  #ENC[AES256_GCM,data:9sLV5naCMjyITlj5PBw9BG6bZudiSLlb6d/+8Z7vkZKftBeyGNBGahTDPnbE2Usq+INVFcEpSw==,iv:CNseTr60EleWJ4fBhIqjpJUsu/4tZeHZ8AeRsGemqa8=,tag:liaG06uyghSTkjLTdyzx0A==,type:comment]
  compress: ENC[AES256_GCM,data:+hXDHg==,iv:gZIprCtQzwNOGORsoSQOZbyQAF0tkwjTHUZ2TfG0ETs=,tag:CVAnMamMl/yRdEyYSG8pjg==,type:bool]
#ENC[AES256_GCM,data:eLVDXL/BBqMChbTmqX0pF5qnGb5E8Vq59eSV98s0T6l+PA9Fmixmxed0v5nLgfSs+doDkKSbRwhnv/VKjTZO,iv:1Ygc3+B2vVQR95Q0N+BQv+nEyBkZohW1T8fju3a8xKY=,tag:cpauiNf+vAeXziWFgD+trQ==,type:comment]
#ENC[AES256_GCM,data:vKP/Yys3j8Xc2D/FU6OXrX0XbTt/3Iv+br5PG3XBJRdTgngvUtYVpmjfFXll/Ze8hTFQJnGy2d6gVZNArg2a4F5atEn3IL78,iv:Fq1oWofSj44rXviThdddfgMK/o/tzdWjlLrZt+79+MY=,tag:oK3tA6athMxACiWI8ZV2iA==,type:comment]
#ENC[AES256_GCM,data:8KY1L4+vt2//A5s7mY3SWTMeotjHZM4QyP0ExwqMA5TVrLGg4GDyd/L6Y9mwOEy9iw2DFB/X/53EGe69rKgi,iv:U/IlWyFYxWVBVaV9DCNk/sh6djmHNmnDwQRktfieBsE=,tag:T0iEyHE2lEtGT+snq2+mqQ==,type:comment]
accesslog:
  addInternals: ENC[AES256_GCM,data:ip4V3g==,iv:ypXomCY/rAEFjjn4zWWP7yc3TII2ewuoWmEEskzyUW0=,tag:rnn/GIzuMtyl+141eRpikQ==,type:bool]
  filePath: ENC[AES256_GCM,data:5TPUQIFSKIkpqNlihptjGQ==,iv:V6a17BT56/YUbBJl2+pZM8t5YTB2TiebUFUd6NplThI=,tag:/D4xEH20yajKeCXXxEZSCA==,type:str]
  bufferingSize: ENC[AES256_GCM,data:+Sgd,iv:ZVltaDmrmR1cF4TqHca9Q3YPRFiBYstotdGX3ePbDBU=,tag:Nvw44yzQxtpEz73e6LHpFQ==,type:int]
  fields:
    names:
      #ENC[AES256_GCM,data:FfdiHddRQBPOjogV0D4OvYUrV+yIWj5bTAnMXVYpJY7ImKPAxLx5Mt4P567wA8/7qGQ=,iv:QWLnwvYUurPsec6p2YxiE1eyJCCfcKecIt5Mzg/5V9w=,tag:GDq4o4bdjNI630k38/n9+g==,type:comment]
      StartUTC: ENC[AES256_GCM,data:qJ3YHQ==,iv:MlvvDQU+7fapoVkUlZUEodokRNDFsPr/eODLXDP5PfA=,tag:l8rgN8wC0n18JVTMH0eTRA==,type:str]
  filters:
    statusCodes: ENC[AES256_GCM,data:GFacmTnE/LxW9b6/tlAfggMGB8j5gg0=,iv:MtbAtS2w1HcvFmHsAclmB//Mm/57WpBWxdOgzQzeHwg=,tag:/1mdND9iHMuWSTED10nfxg==,type:str]
#ENC[AES256_GCM,data:whM1XSA7iMzTL6tOYGyYNLsvAqTA552y0OivDD0+dbtJ4Jwz2/biR5iojt+SuamZcrNdPeifsEwoLNiU6e82,iv:Oe7Z1q7DyIrdQOMat2rUTakvlbIpgqukiPbIpm94Q5Q=,tag:yj5eU0iHwDVxskD0osx1Kw==,type:comment]
#ENC[AES256_GCM,data:r97RQqKxvh7dI2f8GZEtVc2Ni+M5mC0Paz1YaYj4bZYsa5mPdIP49IOriJm9GZzlkpxR7wYARDpjiw/+aMAu1sR65H07li0rb+Md/jPM000/Sup9Ivo=,iv:Jp8s3cZOnne9RwIoGnwTyFMGH3wTpcoAmyfvChid4K8=,tag:cs8uery4WRPdVSa0XhtIiA==,type:comment]
#ENC[AES256_GCM,data:BzJ3eTC5TkhZhb57QIVPr3TXKZjALeroTgxF21EsWSReJqI8/+UxmcrumbQEefRNW7nqnBbvIrcqQruEHH3o,iv:zylpaBBlgV9kmYUeo9c+zvA3hbGBISgVZ35G4L/9rr0=,tag:gj1jVwNQVWpbgvAiwr8GOg==,type:comment]
metrics:
  prometheus:
    buckets:
      - ENC[AES256_GCM,data:9YTP,iv:BneG7HZuHwe0hzWR+Xzd70n2ZDgPkjlMa8CY6P1FGGE=,tag:5+FvShMhEJJRLtdExarRRA==,type:float]
      - ENC[AES256_GCM,data:jSVo,iv:8AyTLp1Vw3UVKW6jV45UB94z/vHn9lla+7wUJwmg1yU=,tag:7ERQB0T/gu6M+Ouu9yKj7A==,type:float]
      - ENC[AES256_GCM,data:YubG,iv:g3oBQ1pZsed9oYjV80+BsBgiHL07Vy/DwLuWjPmGFOA=,tag:FujywDhqvqcDy8XfG4nr2g==,type:float]
      - ENC[AES256_GCM,data:8A==,iv:N+bgEaMOQ7YtYsDChccnan67rHkWp2Tg2b0B2OOByj4=,tag:CyIyjZxZ1Z041AmAYyR4Zw==,type:int]
    addEntryPointsLabels: ENC[AES256_GCM,data:9XdBFg==,iv:dgVoGm0ZS018wyCBdJpnIjf29/YA23mVa4QM2fOZnWk=,tag:JlbWyZ0vI1JQ+SDv0Um1Aw==,type:bool]
    addRoutersLabels: ENC[AES256_GCM,data:pvkzyQ==,iv:Bn3ODX8Fef3uiybcTZAHuqnv+coQLhGxZML89tKCiao=,tag:oDlyOBN2LjrJFSTOlSR2kA==,type:bool]
    addServicesLabels: ENC[AES256_GCM,data:Wwdt5w==,iv:OQA1WbYHpWYJVjd6mUAPf9iWzxknVAogTG6IPnfFMSA=,tag:kyES16OureAhfn7u32jmeg==,type:bool]
#ENC[AES256_GCM,data:tkR944ZyhTxg5ZtdzEqG688U8C0YaWgXBlW/UtDY22fBII+tADzHjS138r/zSx0menMPVF3Kfcuhq4TSlASC,iv:jhoqliL/7l8jLVhkrrI77SPNKD7gQhso5DtXI/QizFo=,tag:Bb8ctXaOgFU+2WqmUpTuJw==,type:comment]
#ENC[AES256_GCM,data:jEWLX7MFjXU6quY+9PcjoqOLDVsGHX4Zd/9rOPYwonncGqRSiu2YZvu1VlGi4kJ6dsOQ4sbcQpDgU3gpvhmDz5Kys+m559M6YUhPXvxUyj81tTMkrTgvUgzlB85P1VgMa+Iq4qgUmOD1My6jlloWEVwPtw==,iv:IDzKt2QNMfgM9rJqx8d64V7jySgnOknGp9F9niAeAGA=,tag:u7xQTB7Af+JkcHlTDUfx+A==,type:comment]
#ENC[AES256_GCM,data:Uk93Z5pR5/8zcarOLcxF2dbynDAsCoiW4Ve1SIeS1VhFOPfXJbaEr2cw7IoqyTsKuszaQYNECgsBzB7XYKoU,iv:k3NAXNyPYeP0BT7I9cRcceZH1OmndimjFV1DToMGz/c=,tag:Ypv7fLCwtkwZsaoVdF64Bw==,type:comment]
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: ENC[AES256_GCM,data:P7mJdp9JGhHqWQv2vsDEBc0vBWQFpUXXTod7nbT402i6JVD+T/kWi6ltx+ZqswUrKM6qvtcWTw==,iv:RQzCqGfniE3rzaTIBetWYpBoea0S+1iowY2hop+Ygfs=,tag:SG2DQcFcjurbsyhPLZb3Aw==,type:str]
      version: ENC[AES256_GCM,data:2DyYMc28,iv:HBW/9nrGB2FTwEEDMNO+WkWM8aLSfF1QuDjjZ8DUWGk=,tag:06b/0xlWwY5Wsa6vp6uPiA==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFRwQ3NDTzE1R01CQmxi
        NDNZdGVETWFSMWE0bnU2M0J2QzFYeDM0NG1RCi8vL1VRYlpoenZhWk81WUE3UFFJ
        Y29pcDM3UjVVb3MvcnJjM2lxRlJ3NTAKLS0tIElyNlNybUxpdVQ5NVlham9vRktp
        QXBpV0JudDJTcHdRclc2MlpUTGEyQW8Kuwdf+fE4o53AV9nisqtrfhulx6KAIUF1
        PZqiGq0wfZl0onatZ1YQp7HXLNnPyfBeyi41Km8mAoTfe5eAwcjfEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T17:20:14Z"
  mac: ENC[AES256_GCM,data:liDG/r6dGlzvaqE7TdxC+3tqkTdzvCny4FT+ogC5mY13DMlwpTO7Y0wSIy9GBwAEpBihJkRMtLdzlyz5lLMX2lZPl1yCAP2V5p+zkpQQmUdzwmIX7K5ME6T/02pccdnwSsXiGQDF8KNoI+cYVW08XBjGsCbQquqgKkSaOwSBjSo=,iv:Iigxo1g55yTPtpqmSiP25OxUTwiohwZArRZcbt1TPQg=,tag:cV+OTPzZT2JqC+MhPSQN2A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
