#ENC[AES256_GCM,data:oB2/EGBkGDRwou5N8E2zwGHA/w==,iv:4wf9SgHkqnRG80D9JSGL7FC1qdq+iCYYwcw6fH+5Y7s=,tag:oBfKM44HWcjQiMjhcCwNVQ==,type:comment]
#ENC[AES256_GCM,data:4Ma+osxAtl7TCelafmvM4M+q7bZgGrUBOCkqPd2WNhTvz2rwsgTwKERE5Tf02GI7v2DYSjBI737iSf2ZJvYO,iv:V4JJrPuhOxG6sIe8ZKPyg/nJRv4+xd0w9G8HV/XaKH0=,tag:nTOsOGb529AgtQfMI/j0QQ==,type:comment]
#ENC[AES256_GCM,data:QQ/12Veaf3i4bRQ60+yQJDpKZztg9HxXLnhFGcu5GzMaJm766ZxQO7y/EOFxR5rgj/mlNy5kJ/FGm4xc80rJnAAA36ONBZbQy35RF5Om4DVjlcWypxN0xUiyPw==,iv:XuQ6SaYkLceZipDtAJPvLKFSDiaHI9X1nRlfRAlJrDM=,tag:d/3kLjlqsAYTnS+zBeuJTg==,type:comment]
#ENC[AES256_GCM,data:0ra5dQG4yu/1K4E0eLr/ixnz/d3WBNt/4mvIfVBxC1sRUSUZdStwMBSIfTQ8VMigoUPGWIdGPlfNbtY4kY7A,iv:WkJ5RG4RA27RTWXsXuo7q104XqvJwCakdKA8RTTK6E8=,tag:nXEWc1PtsJP8n7lIrUXXjQ==,type:comment]
global:
    checkNewVersion: ENC[AES256_GCM,data:CZIQOg==,iv:i/X0YCJilI1Eq1iTqudP7m1O10/LAViNk8z92jRqHLg=,tag:72c+hwvzRFf53v98t7+dSQ==,type:bool]
    sendAnonymousUsage: ENC[AES256_GCM,data:jTZVSWI=,iv:gYO3CvpaWhzwC6pO6gCmVUE6TToBZJdSRfVPfUnrd88=,tag:pyW0dR0dyf0y5BNhFgTeXw==,type:bool]
#ENC[AES256_GCM,data:NgH99/2zu862PFjFBLDFpmJk2c5XSmtvf3o0wsSlSm1YIGxId5GHf7AFDT7xmFMkWiXAYXsxaBpjucrKH2FG,iv:8f7SIksHwpSM8K3o6Now710WuPkUWzBKEcaK9C6qgLU=,tag:oQXRxLoqvpgvCFdIDd4quw==,type:comment]
#ENC[AES256_GCM,data:3BlIxFcd8FMy9pcv2YSpsCVd,iv:QqQpVfnuRgHjaPjXUrc2KbLefnIP56e+dY7w1m/JmME=,tag:tbBofgieKNuXyleacZ4+iA==,type:comment]
#ENC[AES256_GCM,data:fNElIK4yOkw5Ki1lSXQyqqT+K8ZbJlMGRsT+jndGQOZ/+AVQhct8W2WtagOdsl0GJh/YC7n2NEvxTuKvwKDR,iv:OnX5FrhNt8lWAWTir38r9/ohWGw5aWQKOGOPD2o4dZE=,tag:rg+yUaIqXf6m1DcoZnFxFA==,type:comment]
api:
    dashboard: ENC[AES256_GCM,data:3dlhaQ==,iv:NQ0RTB0uUR4/ETPCnGTRi20MlH0bi3T5YoWw2sQwEmU=,tag:viY4/pvW2vhi3l1bH+rzWQ==,type:bool]
    #ENC[AES256_GCM,data:AA56OgKOMzw3I1cCJf0lfzB6leYKEWYIbbTB3OYu,iv:36CY3VurR4ybzLdREDsqW9PhQfQj5mW/PRWmdioQVq8=,tag:zKfaLjXLiYjVSLNp1j0LZg==,type:comment]
    insecure: ENC[AES256_GCM,data:IWQ/3gQ=,iv:krqgKnXVmJf+TM3AUyJSO6i/Ez6LUs5OWKaCQ/wOv44=,tag:KziPIGFacv63bdepa+z+WA==,type:bool]
    debug: ENC[AES256_GCM,data:Bn+5Cg==,iv:CuQzMgMeUQAVxuh9+cjcnuP+6UPAgMhtVbXLZFmyo1g=,tag:sQqWhbCV3nyd/uIhi67V8g==,type:bool]
#ENC[AES256_GCM,data:0ArN4O8Tzrkkil8MtPhADdssKKMjfjDkSrtrvzINNXMufhjNYJV4oG9Ez2K9f2lDxivRLbXbGB8QBXA74ntf,iv:ut4shmbd1hLzPYyun+95gHFBzDTPrJjlp7UCaaId/cE=,tag:VDlPrQ+dMOTHOp6LWX/KJA==,type:comment]
#ENC[AES256_GCM,data:+8jfi9r1X3mQDI7dkGs6X+UQji9+YyC4UDRCFO7O+da+zLzyIE0AI6BcuN8LVQYBvW4pWrmuOBtxJCqaWHj+a2I6,iv:B39CoYVx6+t2McIM2C5sK5KH1ywS3Hyc3ZWpO98a6JY=,tag:GHdpSLkbzpagGNwZyY5RTw==,type:comment]
#ENC[AES256_GCM,data:0R05dG1CIzXHWARFwsZUvFrkG0ZCe0EHueQyt0q3QckK5cVariuCMghXbEmOP459ZM0EW2QFsujGNLNWGVj3,iv:F279gV680GzksQqyRqLqiPORmtIJ2cbe+6QmSb2N52U=,tag:IfneAKdR37nmygpAhZ/9xg==,type:comment]
entryPoints:
    web:
        address: ENC[AES256_GCM,data:VISA,iv:87SoWl0hRNK0AZmXNroE+AIPbdwWgNHYswFP368gXls=,tag:DLEYnC/bByGCAG0hvTvXHA==,type:str]
        http:
            redirections:
                entryPoint:
                    to: ENC[AES256_GCM,data:Hd1r0B5OOdl3,iv:U5t0CgMLtpUsh5fc3inRBqcAycEL/KhCnGMxZf+/HjU=,tag:t/mho0Od/0McFNVLU1ZDMA==,type:str]
                    scheme: ENC[AES256_GCM,data:9W9DmNo=,iv:cohV/en8Rh41h4agvpvVYwGJGmwGvTdR12WBaVfS//Y=,tag:dlTYXyfci1gCnReLvPWBxg==,type:str]
                    permanent: ENC[AES256_GCM,data:fjZ4Hg==,iv:RkPhmynn9NEfJ9KSO+3ofOBk+OmpFykrC1lrlsV7DXQ=,tag:O4bY6kPYAPu6gHXnJO3zrw==,type:bool]
    websecure:
        address: ENC[AES256_GCM,data:9LZF3A==,iv:QQuXxNm4cJneWssDQ55jut+QaGRf+ssKjdYwQU0tKZA=,tag:3l91UhioeppM3ZhLmHphhg==,type:str]
    smtpsecure:
        address: ENC[AES256_GCM,data:+bFN+A==,iv:2z6T7Pdb5AJPt9YUHLaI3hVVNL7SPUINvcIqhsjtIZA=,tag:kWodvpA+ddhPz8K0R32nWw==,type:str]
    graphite-tcp:
        address: ENC[AES256_GCM,data:83FuPXiDuTGM,iv:eh1tG4pCz02Xb1sAmNliGM559RdfYFjska0rhdIctZg=,tag:ScijBdexIfKs9yNpIUcQ1g==,type:str]
    graphite-udp:
        address: ENC[AES256_GCM,data:ilHTg4C1T5Yy,iv:e64lmxPonurZTagD6p6xgh9xw0TJeR5yyWyDkD4vI7w=,tag:bWrH0ktUQSz1VPV655XZAA==,type:str]
#ENC[AES256_GCM,data:UUDsBuX5gyULZGzkAnZ/ghGA53RLBZfE9mXfVTid/GEkZT8RS1rFixt9Y82nB5jqFvwOv4y+BO7z8bANAHCG,iv:ywyl5ylkHL8IY2FiYg5aN4gE0ksR9KP/bbJkfCYTLuY=,tag:lkz7aLhfumqCUFqaL/Cp8w==,type:comment]
#ENC[AES256_GCM,data:9RZfO3XQvxzG2Mj9FE7FRwqEZ5OM,iv:e2clgaFHQ2lr1Q0QhPOusKyEBN48hZs4Ij7qhnVwziM=,tag:8TPXu5ikaPMySdfL+SIhzA==,type:comment]
#ENC[AES256_GCM,data:8l9WU5K8oVJ6J7nfrRx3pTJDJeBWiVqj273BQ1Hc191gxwOHuEcQKD+too+8oLzV55YfvPH9D/3+DuPFTu2V,iv:Clfocb2If4vpS6WVljzPfxtHKA/2j3jgCPEn+4qt8Oo=,tag:+77k4UQccnwkYg5pZVKffg==,type:comment]
certificatesResolvers:
    cloudflare:
        acme:
            email: ENC[AES256_GCM,data:Wery3xPIu1AW5P0cPLjgVPfLjiWW0g==,iv:/APL7nffbr4J5pa+OGqnbk38Qus9fgnlmD5Xr6pDhbU=,tag:TT7WwygBs9xht33/5yUn8g==,type:str]
            storage: ENC[AES256_GCM,data:NJNR8CPfWzQWbN0BxcXT668EzhnnEaYtlCn+YQ==,iv:4kFHQQ1ll2rdvv7BzWhhqyKlrv24p0W01DyVB7jLjLA=,tag:nuQba5fZM3BjfdKShVH1ow==,type:str]
            #ENC[AES256_GCM,data:T0YXPkiYFnbhIzSo+U7omRB5hSPZbJI7Lv4WBmKokNw777umc6ZxCrsvMjZdRT5NN/djvcMndz1Zp1DwrcHypVXD4w==,iv:hKWcpn37v+W69NaZraMuzzFyJprPm4hYevlSvwYHPvw=,tag:Zn+QWcqVMSdd6n9OOvfmag==,type:comment]
            dnsChallenge:
                provider: ENC[AES256_GCM,data:EjRdoA77zRVOzA==,iv:2qBxwiToHFIrGnMGNLJMD+bTOYtpbctLCz4mtmhk/WU=,tag:dUfyu+82gplWEoq8FNJmnw==,type:str]
                resolvers:
                    - ENC[AES256_GCM,data:ORwB9OlXmGYAMQ==,iv:Bp5oRQLFhKidv9S8uRMliX50THIAqeEFWqBPw34XH6A=,tag:DUW0v7ZKimNshzErf122eA==,type:str]
                    - ENC[AES256_GCM,data:0zEsXUO4kEljnw==,iv:7b2suoWq7NsIoe4jiT2Yxz+9vLAgyH9TvhZPeH6ke2c=,tag:yCbdqgl+M9T9ELanEAYq4g==,type:str]
serversTransport:
    #ENC[AES256_GCM,data:eJrGugAM6GRbvW3AQLd9snYHXVhTERlBZ+e1318mHE0jiG3ggk1+ZKNaK4OeDc8iyKa4oFs2fvoRj8Ho9ZOABsxW2OY7tMvuwOeo8P15O9P0cg==,iv:oVBRNYt+ab3CPoXfmpORLH5mHBa2wGFfTXkhuTNBre0=,tag:oC2LRNGxgVdhupy1pjirFQ==,type:comment]
    insecureSkipVerify: ENC[AES256_GCM,data:sl5hX4c=,iv:rWwYypbE/ZQz6iV7MsVyCKtTGhVVsvAwva7cIYkhpqc=,tag:AcExP1t8MRj3wZLmnAqG3Q==,type:bool]
#ENC[AES256_GCM,data:2D4xAZvfB4n8fLvfI+VQLn5oLnEQlxBDBbjhGioGUwzibbrOkSO+6WGRC5yBY2/UnK05Cm80F25haRtwB2pk,iv:HbcR/iafLam+EixYRUrShUwBRVnGlFGCKISnxnoZgs8=,tag:PlNLiogUNyPs/Fc3OLPeGw==,type:comment]
#ENC[AES256_GCM,data:8K6f48jLdL9sEQaLO6NfIWFjiMQKKpspun2W/HD1DuFTBxim0CKheTyx8zQyHtBFGMxdyB/t1fySf7sUcw==,iv:koRDGPvzgb9rqJHI9aJFT88O1jolf7T53yZOiJL5MpQ=,tag:EoHXC+Vp7pwldfFHi3tuQA==,type:comment]
#ENC[AES256_GCM,data:BAydd8QmHz0Iudc2pPS9GiPxfv2jI2v7/1r3E2SFOPpKaSQ+B11JzaZulhc9DV30eayE/ou0bxXJ79ywObxN,iv:umcyQeo0HU8OLdiBYz61jOxdQUjoZcmwnaK3M4wFZxw=,tag:FYYeXiPdMH3AVLmDbXezFA==,type:comment]
providers:
    docker:
        exposedByDefault: ENC[AES256_GCM,data:K3wrFJ0=,iv:YMt+pfWwsIYcEWlM9U6mMwhFYpJS9lDSQQlOga7FKB4=,tag:UZTVfxa6cnq9fKOS6Xa0zQ==,type:bool]
        network: ENC[AES256_GCM,data:nX4AtOWqHw==,iv:QX9m5sFF44qk1CoZ/XdZruBNej3sJgUamwKgNyjv/RE=,tag:t7Y6a1S/GD0Roo+/0FCzsQ==,type:str]
        endpoint: ENC[AES256_GCM,data:Nv5XUtkcssjotcQXrmg71Voy0OBsHwA=,iv:D9f+tnJX2liG+wbob3yyFsi7P6bl+zBFoZNUSzOGz18=,tag:U5mD9EZVenVUZm/ApYH2Rg==,type:str]
    file:
        directory: ENC[AES256_GCM,data:+L+roYFZDc04l2vr,iv:f9zBNOfN5REDNChQQ92yeQsbMYRcgEyrWZBRcRuwJno=,tag:Ct55OULz2+tzv/sRQR97Hw==,type:str]
        watch: ENC[AES256_GCM,data:1G6Gdw==,iv:bbk0xnSepjBd/fk7y+heUeCb80HjKwRJc/0oqn8wQJ8=,tag:dui9FGEU/Nu7x6Ed+07bOw==,type:bool]
#ENC[AES256_GCM,data:rEqsT9qeNmDYk/ZLp4GXwDVE1uH3bC0/y8uA5GvFVAM46xPYf6KwKH0oO7p+T/R5dlHYfeexKDZ2WKD8PMsv,iv:n/qAp4cDP+mxJDOrzCfOKnEyGZsjHl4uR479eYFBGkU=,tag:7z7tTlQXhsnz1LNLXCcmrw==,type:comment]
#ENC[AES256_GCM,data:bzyXuLjKUszQeP7GHZzI9UJ6rGqu+VzGAsBxCiLTEaG2m4FThbcklWUiU3FQzRaurBcri7SNo0jSbw==,iv:Ufhh861EXgC34QyLiiRxAsM2YZQi2rsCnGfUS+ErF/U=,tag:gu/vb+rx3BnbpA4DzIYRNQ==,type:comment]
#ENC[AES256_GCM,data:OUmyyGFCxuH0aB3SXL9IgqWcIB5PKaqxj6nmjLEuZrQVQyrx2JrWsqL7YDqDLX55E/ymg2W9Hwr6O8d1tC4l,iv:UJ4khrg1wlZev9dfvLoC0Hf2lbb8C54GzJrlbjm6G40=,tag:qFVfBjIA+f8Y4xEPFDuY7Q==,type:comment]
log:
    #ENC[AES256_GCM,data:Vk0TIqhJu36GxxTQlPAmYSva7hXE3qlk2pLolbzcDiykK5inYELG+CmJCMHjkYsUZ196iP31wgYHm9AMWaw=,iv:ltR6riUNz/qmkP9DXeWXISb6deY1ctQ/iaLDv89r0jE=,tag:l0Zgdan/eQTYXBOm4W1CcA==,type:comment]
    level: ENC[AES256_GCM,data:2awSbq8=,iv:BWNYUyorBynRsveba56eafL05GjZ3DOUTuRWWJh8SC4=,tag:mbY28KCs7XIy/CeSS20KXA==,type:str]
    filePath: ENC[AES256_GCM,data:H1934iXda7QPboEtTYf4OrY=,iv:YPcaCbNL6hSyuh/l+bnSUfPdhAuMSCwGOjaMQxSVo7M=,tag:vU81Dtfn+dmhodkfW8NrpQ==,type:str]
    #ENC[AES256_GCM,data:uqAhoRllDPjNMidU0g==,iv:KlV8OcNEb7dToIC9znQgyZoe38bqXbEbjed+IDOz2HM=,tag:uWBV65lf6pb7GX1ChjBGiQ==,type:comment]
    #ENC[AES256_GCM,data:IFa3qqL0mpEjkjeOY9sZeePvYt6aPHAY08dPeeKsATVkzPS4QVFY0YGOBpDdBKe4/A==,iv:p69YV2Sd1g1tP9wSR2awvowgNMYk8qXN0MJ9dqIXJOQ=,tag:rjcndGymlA8qFJkK7C1v5w==,type:comment]
    noColor: ENC[AES256_GCM,data:qRQDpg0=,iv:VgyhKvhLmJWx8fFx6jmQ/Cj/F4qGTQOiLgCw7/KO3/4=,tag:AD89g/cvd+xkoaeG6rF9Gg==,type:bool]
    #ENC[AES256_GCM,data:3E0k0OpYZclpfSGQzZbFW4w3jjkhWgbptCFQhxJ3BpCf1D4=,iv:3L8quhbOIIH3bfF0LR9RGwCBd73PVWNsHYWaDKmwo4Y=,tag:Y3qe0qT8/RgE5NeZlwORjg==,type:comment]
    maxSize: ENC[AES256_GCM,data:bbg1,iv:mvErD+zniwvwwShqPn86zKmETl8NhpT3Tk6KlPSUww0=,tag:dho0qo6Uv2soQAP80jePSQ==,type:int]
    #ENC[AES256_GCM,data:GjN91erC8YUTHWOC5xdsy1in+gu08zmB43HfWeNedlsOWP62IzI/qRRpETaWHwl8rTxevSdJrA==,iv:2YZju/Rs1M23SQvGwhN0XwDoH8JjzFF5EXCxGKJNa0U=,tag:jkN4qz9EYPDESA3V/b8V2Q==,type:comment]
    compress: ENC[AES256_GCM,data:2dKXQw==,iv:HvutkpNVR+h0PfBrnVdIBlw8oA8gOxratpddsB9qn4s=,tag:IavJbdTCjutGg1oD7XOFKQ==,type:bool]
#ENC[AES256_GCM,data:lueJqLQc87oocueC7ZYlF0Zyl+WLyMRdStmKpbvXbFUv5JEcMgkGY5Sp/HWrLnsiNG+8u7m0py8Uy0moBDul,iv:T9fhgOErNFmh7SCOoDjWISlF2m607URw0PFUlXuoF94=,tag:F+tgiNTaS+sR/2F+WzN31g==,type:comment]
#ENC[AES256_GCM,data:zeHuCHiJHSSttrRfsNCUCK+qD73zmpowiAZr6bbc77qjIbJarCZzdvrXveZ+1tKo71LTAihoXmBnq1zSR0dn3WBQjVGaBuaX,iv:3DG3AIgNNZ2cSUheovFebsrAsjUDUMtxJ635GK8OeJc=,tag:HguQ87wxE53pSzHo8hDMeA==,type:comment]
#ENC[AES256_GCM,data:hu7cwJt4gWYozDpFQuYsO19rNZ3DOADUd1Bjy88UA1UjML6NEtxhpsDQVtOp7boZsYxOorfW8xPGlJ4mJtEG,iv:rSUFQDQBO/rx+ZYWoZo4XubLq/ZWnNmwGg8W8op3vTU=,tag:JxSrI3vN16oOq4lormLetw==,type:comment]
accesslog:
    addInternals: ENC[AES256_GCM,data:I53nCQ==,iv:Ue0Ea1EmZDeJQknmB4CY/OuJ4FV+x7W2yLYVbOlxyj4=,tag:EsiKc6ttduZZIDfN6aDfIg==,type:bool]
    filePath: ENC[AES256_GCM,data:06QmM+S1xCBs2pAZ2F/+qw==,iv:r0tvWY+t+Uf6aeW0ZujDnUt0WhNFMgmRysGGGGCdCDE=,tag:Y1WmHzwtlKLQizLl1vVK9A==,type:str]
    bufferingSize: ENC[AES256_GCM,data:gYmE,iv:r8W0GKOmE6/kT4cCxlemG6y16WBIOTbtD+wlIKvcSEk=,tag:G8l7zFWY+IGZNPZO6u1xEA==,type:int]
    fields:
        names:
            #ENC[AES256_GCM,data:9lDVjX3SUy4tZvu4mWkwHI91mOA3WxeRomGgYFglewn68WAyI5XHGU9zaQ9e0vErq9o=,iv:kFwn2a9XL/1f8+PuyS1/IuqbDCLiztTaWCCH9fWo2/s=,tag:TPG2KZzomXqEiIyTJzb8zw==,type:comment]
            StartUTC: ENC[AES256_GCM,data:JGFRKw==,iv:eAMtpTWjzwK4x0J+3BRx1AeEYgjesDORtRjN1No9SHg=,tag:DFO6E36m3SYc8FR9jytJag==,type:str]
    filters:
        statusCodes: ENC[AES256_GCM,data:mMjdOrCl4gcEzMst8vhEjlhdAJVcnm8=,iv:K6Dij8WVqZQ9ugdEGtQRrBKKQCVS/zznHVNH8kXcG7o=,tag:3NzxvmZV68TUxO17H1T7MA==,type:str]
#ENC[AES256_GCM,data:xzy90PYDPWEC9PEditiljI83/aYv6VNrvAEEh7CvJ/TWC7LmGgdQ8Hn7BlWqlbRUPBBfXd7oYVDkEyJUKsID,iv:PszXahUs1j2zLtn7gbT6IbCBHo7xlEg/7zEljk/WZC4=,tag:gNLOBF1yXeWLiP7On40c7Q==,type:comment]
#ENC[AES256_GCM,data:CdYrfBp1/Atbdv0fvbdB0BRRH0yAIdV7yPHeHSA1apKVCsEmKGxyDgFkQibwrR3pl+kN540voAAeeUFF8b3YeAlStfE3S2T3ROihBiU+seVj7M2e2OI=,iv:+I1dcT97oZeWOpJnJaCloVipqJ4qe+xRbEw1FqJRkAY=,tag:LOoWiCEPAdsfsC4HZ+YZdw==,type:comment]
#ENC[AES256_GCM,data:+QrLUxdtx72A0RoPcRvQQvVqbmfVf0KHc9zxPgrPMvzmc8u0twYMEsXQOR3bsVtWK3FkEI0NI46wmYGp7sof,iv:AF7paKzp/Jz9jUauxknVuBzQ4d3/uk11C9uADmX+xog=,tag:J0VYngrgOsNVsRXLyyyURQ==,type:comment]
metrics:
    prometheus:
        buckets:
            - ENC[AES256_GCM,data:z05e,iv:s7sy639updD9w4t/7zVsdPWmpIUQOiYTXa4XGYplIiA=,tag:qOTl2rkwIizZX6NsCNN9HQ==,type:float]
            - ENC[AES256_GCM,data:T8GY,iv:vhoph1GCBfvrcq1SLviBkOpRWSm99LrNdFNmEp+F+68=,tag:kRb+ZHTNRIy1MIrdhMBwZw==,type:float]
            - ENC[AES256_GCM,data:mFGu,iv:PP5y2ByGrEYBwSbFzDcMIMsJxE6Emk4hGgVyVpse+hw=,tag:8WV2na4fDnoKXI6vvvNmcA==,type:float]
            - ENC[AES256_GCM,data:KQ==,iv:OMJhaFy9gsKt5SddO3x4jyjTmu12qZ7vMzu5NMlTOdo=,tag:0+3IQOd1t12DUNtbugJ6+w==,type:int]
        addEntryPointsLabels: ENC[AES256_GCM,data:G5B8jA==,iv:aNf+QSw8LaFEvpvl1VXtHb37i1nZpdimzrmtfTtOCbQ=,tag:RIcsVPtFwgFYX9PTJMgBNw==,type:bool]
        addRoutersLabels: ENC[AES256_GCM,data:UzbcUA==,iv:r2xJaaJCKl7eqQIuIA8mfht20lSY00ZvbTFRNya5rvU=,tag:uf0KD2nkbdx6p9NfziUlNA==,type:bool]
        addServicesLabels: ENC[AES256_GCM,data:GsS0cA==,iv:mQ2DrWXxyP4wMNRul+UWl7rWtQpci7x2EEVkt4ftiOs=,tag:qYWe8DWNjbCe7DPuMUPJBg==,type:bool]
#ENC[AES256_GCM,data:Iifu+S7d9i1v9iYlTQSkTWiTmSigSltjlm1CSA6uy6DplbdiHRkCerSjy3skDUHLbexQ/UuzRZ6A4Paorzkd,iv:nX5Kp9SclH1q6q6gFda5SOv94tMXUAzQna+Jt7dj5Ps=,tag:9nip9B+RPnLZHW74IDSt2g==,type:comment]
#ENC[AES256_GCM,data:/XbOC1mOPJnIFWiixqYneccP5oJMy7/C0gWg7jrVIDe395vKXNbp6au6O5Q363bCVH5oqHBmUl7rJKNuLMS0WTR8vstnF5Csym0da1dKq3bqp0FgL2I20ck0JK5zc7JTjiTRsIm6/1Fy9Z2O/WxPK3VINQ==,iv:q0VSIi3W8zkyQmXqJ40yWykcVPTGljFboHvtpsS0qCY=,tag:hJfrkMmk4HYqjqRsjjA1lw==,type:comment]
#ENC[AES256_GCM,data:BZM1c8+Aod5J8pU+q8K+qFJffWkcghjRcmqRZqISNYkoc8L8QV6Gr3phbuQN1/Z+QVC45T23S1kgWYC1Rigf,iv:OrNcMKHbdBf6tSa3Xpq/+ZXsD3E36V2XwFgw/wJNAIQ=,tag:PP2Rwyw2cvGaT6YHexLc2A==,type:comment]
experimental:
    plugins:
        crowdsec-bouncer:
            moduleName: ENC[AES256_GCM,data:H64LMlKp+zYb/HIJBvFPkSEQeTA8NVF3wCCyvYsLGPoUBUQtoP1nyD8cHH2pYjUbNd6o75SIkw==,iv:zUGUqHvFJp7cXdRTiFBrL1N6drUKtKAz8tWJ3ZF/1/E=,tag:lIeawRvC3v5QnDRhtbjxqg==,type:str]
            version: ENC[AES256_GCM,data:MwMjg83r,iv:VR7nnpDmb1XgazE5ZM/7R/ckS/kt9o8O0fah/Jf+fN0=,tag:u9ugi4JLFoWMxiQIdTFmWg==,type:str]
sops:
    age:
        - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUkdLd21wZDBVc1pDTW5I
            MS8yZEhwR1J1WW5tVUZVb2FwUjlnT0dzK3ljCktVVGxUNk5sM3VocGJWTXdoRnkr
            MzVWeFBDTWZtLzdaQngrSTVkTTN6YjgKLS0tIEQ1NEt2NjVUT1NoaHppZ1hEazky
            WUU0V21JZnRSWmJrTzZVaFYvMWx1cWsKVvslAyqj9qE1HmrSXJERIKED6XnpHMiM
            FZ0hImAUmCi6fa1fZtr4FMS6NNlFFiACpXd7DkDjGzld01QCJbL6ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T23:30:35Z"
    mac: ENC[AES256_GCM,data:17V0y/meaLXyFxEiteGINbr3hpwALE018d+xi5WJPbWkdlHC7HjPnBZciT8Vs22DFtkuSQshzLQywz+71TCc8PxvRTi9a4FYOalqbpyH9yznuUJAk7V2wjS1tP2PoYdR+nq/rN2hLAsovY6ZMRMgQFPY2IoBE7YV3+/SgRspmD8=,iv:E6iDFCl+KhLwIefeMVT7RdRK830YJOMULFxq21WIMVE=,tag:9I88XPCsFJHfNKVGkjyUsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
