#ENC[AES256_GCM,data:XfIdpIcxqS1Beojqeo9f0H80lw==,iv:tSX+Q9Iz5JHHzOgR56AfDTV2X/T7XwZ/52Zh/398hoA=,tag:OvG8035EGtekysGZyjdjLQ==,type:comment]
#ENC[AES256_GCM,data:Zel32pj7tU9OLClola6X32HhYucGntJd4DdysZP3LPXJp5wwiY2WvevFq7eSYqYl5JO1+KUYylc9Kc34tRsN,iv:UnQnGHhe630U5Ka/CXdFUxfbRMCnvvdfPu0V8oMTes0=,tag:ZOPbo3JoJmFfgz8QlTB54w==,type:comment]
#ENC[AES256_GCM,data:pGTH3zZSZK6kFdgtp1LqCqv+oUpQoz8ZnOtCBkHNS5Doe3niSvy1O+G3p83CcOWMJB6ZSh3LMg7VEi4CabhWBGpbT5XlYOCUHZe/riASjcqgDGYNMqU86B7o+g==,iv:HuFFa7fMpsTwUuR+d54hyebIJhgwzxRx3nAA6nPIc0Y=,tag:0w4+v+XK1vRy8Yhm3SpyVg==,type:comment]
#ENC[AES256_GCM,data:qYUnlPA/L59ikQtP/mHyMjokQDMdLKFdMDEa4jsh9L62zci/q+5FwliYsi7FMET9Y5bx2X8z1P/58KtNvcpT,iv:5BAiLqJcaJyHbgIQ9qerDimcqASd8IdelXQ393r11MA=,tag:X9m32k129yct44QOcsk9AQ==,type:comment]
global:
  checkNewVersion: ENC[AES256_GCM,data:DcjaLw==,iv:Crb1L+dhzN9DKpfW8578H8ZUC+vODzhYyqQ3t/xM1iI=,tag:ZWrk2gqwgc6JAMbSvzq/HA==,type:bool]
  sendAnonymousUsage: ENC[AES256_GCM,data:Lc8pkiU=,iv:fn4Jt7JyhRF9nazby3P9tiwOWAOzgVChmHFl39h/OVc=,tag:t+ipXY7T6ElcusY6OcAhMg==,type:bool]
#ENC[AES256_GCM,data:AEFsxiyoMSuw8PMcSBE/UbfWzPetBGlb9SGUcAHXoTy/4fmowMdFiCftzGe6krAwKfCT35R0dT608VeVzu+d,iv:dHXil9gftZesY8vwBqnQQIuaon0Fkj/TpnWH0rb6Xas=,tag:AeBfrxagXWXyNGYN1BsrJQ==,type:comment]
#ENC[AES256_GCM,data:CCjnh8ctxiSdgdaEiIhj43SL,iv:WvrF1+H8qxAWtQup5Gc3wwvY5sGHdsjapjRShrgq54I=,tag:p5kdMsQNKDZBp4SF+3dFUg==,type:comment]
#ENC[AES256_GCM,data:Qci0t6VPFtwc3j3eMIWU3iU3qwrd+FG/Cf/sI3QA+9L1EjubcmMvfmmK93qW6+blXKRXMsf6E1XI5fDxXHde,iv:0fd0g6zKMdwIQCcNLI14i1zvv/rtltUmPrOj5wiHTSs=,tag:wK4OPojKQ/raQuk9p444dw==,type:comment]
api:
  dashboard: ENC[AES256_GCM,data:1sBGQw==,iv:h3Ebe4SuD3Uzha2ubhApEHnVfqXh6abJuaxSkny0axM=,tag:8xR7DOLuiPCMKCFYWmxfwQ==,type:bool]
  #ENC[AES256_GCM,data:6o3jHNz0mAxXQJr2sGwQkR9Aw9oKayEEjM5Ovb+k,iv:D6FiKx2OIGSCIOulhAIsn1RmMucXWhjbngATJvrOAUY=,tag:DuzILiHOspkiEFS0e27nJg==,type:comment]
  insecure: ENC[AES256_GCM,data:7QGswIk=,iv:W50Am9R0XInc/lQ/9Fx81ZVotROsAYfawPtg7zRxvxU=,tag:Fl2TuZmAwlijvFzzNi3PsQ==,type:bool]
  debug: ENC[AES256_GCM,data:KyjC9A==,iv:O0HD5zmyzBw7L44bwWCsOeyfBlNwPSHHbPRH0Cmww+Q=,tag:sy4mM3zXqehH5cMbXGaKBQ==,type:bool]
#ENC[AES256_GCM,data:UR7DW5zFM2V16cddxoH+0nKtMNoOAR3ederWIJw40qSZTjz09agHy4GRFrG4Lga2nkLi7kfSWoKhC+15N4ZJ,iv:0slWmEdH+umz5UjwRyCo/10cBg4DvCKGykohD6+xYQ8=,tag:poG6wBBT+5o9iLgGKSe9Hg==,type:comment]
#ENC[AES256_GCM,data:ObNwa7eNnqANOFadyvcurjdaWO2/a52Cose7EDjC3vuLl0l8fag6M7Weedfa9lidI0FfHQUN1rfI1GrGQWvywDxp,iv:5ANkdFTMw3Md4PygcRn47zj8/dHQWoCKO+6WhIcIUt4=,tag:ePD71otVc6knHblQVTTIAA==,type:comment]
#ENC[AES256_GCM,data:JwN3k//SCdbQsH8K0PQwKt2LHC7GsVy0aobtlC3CPCoKfW/5LIq7KbRbvuKR6BQ0IjGylHwIHN5QiWN+5LNp,iv:TWcQRKxyj+oDKM/mK6Bh+Y7teZl879tE4aGK7y/2yMc=,tag:668kMFAgN75HymV2ryrBPA==,type:comment]
entryPoints:
  web:
    address: ENC[AES256_GCM,data:FpBR,iv:W0grXZ3spCLL64tB/h07uU1zq4O5RbWNCQkev82iKZY=,tag:ToE99RizuMU0f34hPK0mtA==,type:str]
    http:
      redirections:
        entryPoint:
          to: ENC[AES256_GCM,data:lH1HwK3RsyzX,iv:HWRoGXSsKmiIlHDzA+cTOSPkqYp9IR9lDNOi2ngOoF0=,tag:dJNStfI1iYQ2GSkifPD0sw==,type:str]
          scheme: ENC[AES256_GCM,data:4MerApg=,iv:ROS05jC2v0KFROg9G9owiZZB/qxPmodcIRZGQIjPc/0=,tag:SsK6kOdepECI/FZXbm8IyA==,type:str]
          permanent: ENC[AES256_GCM,data:tbTZVg==,iv:MwJKcek5GV2nfHAi7qujPaOHZDUpqodu0HQoYzEeJac=,tag:wgfcWRH6SPO7Lu0R8sJ+fA==,type:bool]
  websecure:
    address: ENC[AES256_GCM,data:+aZS+A==,iv:tDbY1UhSCowizzr8uNAt0tcZwAtk3QuG368+OgVuR0U=,tag:kxqWzJSaQyjKVhWMBN6LMA==,type:str]
  smtpsecure:
    address: ENC[AES256_GCM,data:J44ieQ==,iv:omkFuYTh0PBveCk37nP1t+BaBgTsJw9chhBu4mYs8w8=,tag:s0VWGSmd1+Pw+SrWgOjebQ==,type:str]
  graphite-tcp:
    address: ENC[AES256_GCM,data:jiGjAlHx9ZEW,iv:M4G3ShoJuOyQbGJwfhX4wdGrFxrZagxV8Rcun+kI+48=,tag:JN6q7Fr6YWDuc2PppYsnIQ==,type:str]
  graphite-udp:
    address: ENC[AES256_GCM,data:k5IZIr9XC0kt,iv:JrPF2rZr8qOyENyB1oGDz2HiGCMiwZb1QhWNvEOScWs=,tag:Yp3h13gOxdfcx8Pl/nHRcw==,type:str]
#ENC[AES256_GCM,data:UWcXjs02+UH6MJuH9bFN+lPJI2WS+eg1oj/1z39ROuTZcZjvFjDZDejGTDjb5vRRvvGZDUYu52CaBiEuaTAW,iv:UJ5EZtU6NmVlbuc41qaz+lTxF5o99KhWaZuCu3yl6KM=,tag:BYTNpr7MlgH40spykoesEQ==,type:comment]
#ENC[AES256_GCM,data:9bdrYQqp09b58jArJjJDnwkXh777,iv:vgo113L+xh+ovYOdsCLmw7itfYknarSYLW1tpWDRkOs=,tag:yKUyak+RDbbteasH8sqELA==,type:comment]
#ENC[AES256_GCM,data:mpm032zdxSBYTIFdQJkJXwxCt/zHVsivXOQtPFpb8OUj/aveLso3cXwFF8je4WRlkPfM4mH3WcmfPJEri0Ie,iv:R1MPoHE57w4WVh/eNXaqC8SR/vP1vaEnHzw5XMDu6Us=,tag:moNZWDMCUtdjdSw5MZi/BA==,type:comment]
certificatesResolvers:
  cloudflare:
    acme:
      email: ENC[AES256_GCM,data:RduIMKjh4TWF+sT4Ame8jwatx2126g==,iv:misuWHWddzW9X3MnQdEEJWkVB++28TR1U7F7Mq9DZWI=,tag:+NbLA6cslrDYXGA/CqwKaQ==,type:str]
      storage: ENC[AES256_GCM,data:fiQrLqnyNHyP1dDr/3JCUGdZ4LvgFFEwh5aSRA==,iv:+zgGE11l8NflDzJSxaXXsAXvSrs5Z2hnlvB7teFgnB8=,tag:oAgkHz+lS47r7G0kBRQ/xw==,type:str]
      #ENC[AES256_GCM,data:gkUDsHqtr9YGgPWADbj3yRzFg2H7W9KFKrgwWjITbJq/izZtKMpf9sLjuF6a5eQs8sWtH2xrqVlt7u4Ntl8m08xpTg==,iv:KGMJhN6hhRMaHUiC/gKlRCBhqPgZ91K5V1FD/GX5aUk=,tag:OiSvEiVKHsaw8N7mNLSXIw==,type:comment]
      dnsChallenge:
        provider: ENC[AES256_GCM,data:EdV6I+ZMAuf31g==,iv:wBzk+PCXkUK6CNPlnVNLt/6gtYW0eEv7uWNpv/dlf9c=,tag:GnNnyVw7FbzFgELYHto8lg==,type:str]
        resolvers:
          - ENC[AES256_GCM,data:BnLVCMNnoLqMbw==,iv:gaZ0Zf4o0IbFTV+slY6Ugq+4h25MthN7SRAz5BD6HjM=,tag:fcAG0np7W3VEWV6SBicfwg==,type:str]
          - ENC[AES256_GCM,data:hYHmu47CR/7JDQ==,iv:BJ+M/t8F0JPJWQ37sWbtddND5LDlDLaZ+n+GyOjFAMM=,tag:9ouzcgNgX/AvsLm6mTyEzw==,type:str]
serversTransport:
  #ENC[AES256_GCM,data:dfpgG/NrxbC7lGicof0XEtUytZcc5SFXLOZw/YRBTwFeEAYCeryEYvNQ00LxR3uguahP+WkDWY70Iy6BvSLX8cwhMhjxK3VCxKH6Ye9aQVNv6w==,iv:428OH76N06YOi3iXOkUKKE5eR/1nxWIBadXDj19+uHk=,tag:gQJNKetG9EWgQ0CGTzUBeQ==,type:comment]
  insecureSkipVerify: ENC[AES256_GCM,data:WfYUjYc=,iv:BBKpbFM/7e6p43iAb6/0ixigLLIDbzBmhyFqyoMERYU=,tag:eW6E4UKvK5N3H7RwYig0bA==,type:bool]
#ENC[AES256_GCM,data:eNA2DsRCbZaIuDiHT2rVNk8CBdnrISQBI/2fF21Soi9EiL3NJqJYw8xD5/nlpMZeBzLzSK+V3JM1RK+/NwTY,iv:Qyoh2ybR6PSAfxxU22RqjpWFL7pfP8J0lBVwr2o+FCc=,tag:IAYQX3qku/ALrIT5HB/0ow==,type:comment]
#ENC[AES256_GCM,data:E90gmCul/OdlPyX+VNX2nrwmbgAxY8nSwciMakNcZIuM5EtEI4pIEDJYnkj7cTLYdaTYLD+VatVAs3fMMg==,iv:75uvDsCsWeZbFQArAaraS/4hI4ASX6DK5d2IicUPOkw=,tag:Uve44HUgCCuIGrrF2PxEEg==,type:comment]
#ENC[AES256_GCM,data:EW1hGhTouaMEd3BgIUQ0dYYHyGOM8kRHxT5YJrqRacVXPNbvpc1JO2/etxcrT8UBzBMfjb0Fbl5U3WpvIhwE,iv:pxJAl7nZt1mO/TfO4p4RtSTZEq+pxmAtXm7OBK7CZXI=,tag:3WubVZlxV0nIv58OwCODcw==,type:comment]
providers:
  docker:
    exposedByDefault: ENC[AES256_GCM,data:wwsacyI=,iv:GrMuMYc0157i167Ffhtg5/69G8RStubf1eiQ60FIhGY=,tag:3RWKCMOJfYTFRkjxra8ZyA==,type:bool]
    network: ENC[AES256_GCM,data:b3eXpAyBWw==,iv:4a4HHGwKdGinC5/BjWw8tqpQBwr0vkOQNS7Tn6TdrSo=,tag:xop7HVUScd/jhr+Xpd6+JA==,type:str]
    endpoint: ENC[AES256_GCM,data:DhxHY161Ujrcqg/ROx23ndDcDzk8Tqs=,iv:87JXndZt1u0zisiC5vsVUvTSV1eogKPL5M0gLt84fTA=,tag:Xx9sPQ3uW1OW8jyWWmkYCQ==,type:str]
  file:
    directory: ENC[AES256_GCM,data:KSzB/Mgc3+qwfqQ1,iv:TxP+eICi/E9Fhnevo4bYJusvYt9bHXb9eTyW/1vxCNw=,tag:5PLcMPbDkhPVU6iTzhlP/Q==,type:str]
    watch: ENC[AES256_GCM,data:A7tnvA==,iv:hrE/Qh6gRLYdhBKf7P+9G2nlaXuHvK1Hl68VncbFkhA=,tag:G7lEs/i6pkrJC3YwICzP7g==,type:bool]
#ENC[AES256_GCM,data:PuZtv+oHJgzaj1xVKG/RXzH/O4wpsd7MWLP2zRHmOkNuVNa8JfDeLxj7a1GN+cpW6UI6AtesUHTCV4duhQ+K,iv:NdE2SngWaBHMdkJJpnp/Q7yAl5zw5YvMnncgsi8y3wg=,tag:j7+FOSrEftYIxEiyqlhGqw==,type:comment]
#ENC[AES256_GCM,data:kngrpNl4TL+C0/9VbzFIFv6ift38Y+vdVXJfbdIcAlEC9I83DxmHqZrFCn6Tyl5wmPNW0FCD77Bjng==,iv:91kWTthqfZO0HzIJGdpqddeFn1TPRLBaAkM3wrTwYEU=,tag:PWRo4E/tqeUUAoGAL7X0aA==,type:comment]
#ENC[AES256_GCM,data:wA1MOHe+4/hgylGlGT5WxkpFQcRbLVAj4sY+DZHmwJA9I5UP7cVZ/JSiFV4EouiuKwEAHCuwqcobb7vtOd5X,iv:ChdDLPelxBhHsYlQDUDRTcuryZX+ZlapWYUnNyoYjp0=,tag:3y7uNNiG+Q1dKDdFOpvhzA==,type:comment]
log:
  #ENC[AES256_GCM,data:MTgBWdpha5gtzmzGWvivMDK0u1vqJu3TMJtp25BkR5Sx3Jyy6wf+d82CA1+tDw2ED6YpM2OHWr9mtq2pTJ4=,iv:pPeGy75INvt4FDDwX2CuimxmC9je8nVFtyVO3i3Gr1U=,tag:3fAKd99FbdmgnSKvMe9OuQ==,type:comment]
  level: ENC[AES256_GCM,data:VYIkHsQ=,iv:9SlHnTiqA02FGRkZG/wanOeQgzF+2+YQpY9Bw8ZWkQQ=,tag:Ipkkzq0V7SzH+/MItvjg0A==,type:str]
  filePath: ENC[AES256_GCM,data:GhLcjM7grWd42/2TCEDBiGI=,iv:rvAeWwcQwvGRGIxqiYnvFogoYFRPJWJMGSFQfHIiShQ=,tag:TBGBkXe3FYTAb5GulVG28w==,type:str]
  #ENC[AES256_GCM,data:2/EItjjcHkqn22k8SQ==,iv:VgkOFcSgv73XnQO1IuOArE99gcptOQMfg7/rvvkmqpw=,tag:PFGUIr8Zf35ZqjAUcXETPw==,type:comment]
  #ENC[AES256_GCM,data:paphgZkm5XvtV3a2CPtOYX+n74yYP7mlw7Qz0RPwYCwc9sarKfVUeE3CChz/ethYyw==,iv:1olrYY6Z48ps/JYl5H41xDTmxJqgpSGjLSSQFi6lHxw=,tag:i2qnkFje0KBlKY+Qrovkqw==,type:comment]
  noColor: ENC[AES256_GCM,data:EgoUQ4c=,iv:xMDCHLVEc52UMEutp5BCMO3yjJdIIpD4L8AasNW16GM=,tag:BtV9xnztwHQT0uQU3qNGWQ==,type:bool]
  #ENC[AES256_GCM,data:t4rJW4DnqbxEAm2GO8zaic42sglvFqIdkFcqorKcrE728eQ=,iv:Kv34i3DGHsMblhV1huzd1Snq4qPVnvneTMt3cJYxBV8=,tag:JiYKfqR0pn+I6NAAqjd+XQ==,type:comment]
  maxSize: ENC[AES256_GCM,data:4SkV,iv:A/iMkGDCsnWZkohP2wjiSbkL/+FciHnJjum9TyD/VDI=,tag:s92gw/VeCMd5a/p6r6FIWw==,type:int]
  #ENC[AES256_GCM,data:0IK39MhgBfg+sI4mHMmoU8p4nX6ss3I65QWGZz4tXFh93yPa/Tlr/P9ELySJvGa2M6aCGDdrJQ==,iv:X5cPakVRYTjtprBhX0fG7dBYlssuBYGBp7EnNfbZnPE=,tag:gv8r1zBYO92J+xXU2D+ucQ==,type:comment]
  compress: ENC[AES256_GCM,data:ye9KyQ==,iv:PHdP0hI1W9Raj0KnB/lOfRCuoMK/xOooXQgaPNgeTgQ=,tag:SFHtxRTf7tis2tHzjQXfZg==,type:bool]
#ENC[AES256_GCM,data:OiY1m7h7VT7QDQn9RHvUhn02QAhr07Mz8uwi0gLyZ0N01qm3+6LbouPtdffiM8oziepp009MveuSSLadrkVP,iv:eU3Ep8f6LApwW+8NRlwkqKUQ7UBPqMroCveGq5/knY0=,tag:tdC2k+8r9siPQ1RlJ7WZig==,type:comment]
#ENC[AES256_GCM,data:NIx9pcNTxU4FZ4203Y787Tz4xPPXpATM9EdKtE/xES2/q6U6Cp+Vb14d0UPS/TUAlSVRc868VIfUXpoRWu3E+w/4BfifPhrx,iv:c/1iluE1RzUkHKrD1C78VQzG8wYojfjd1N+BQHoy1rg=,tag:W4qY0r4DqLfvCnr56xCaHw==,type:comment]
#ENC[AES256_GCM,data:+i+VItpnyDXWjZdboPbKjFIHDAtEBt/tkXdfnJulSyDJheQoxajqL06kaJLtNJTOvEcT10UGpq5YLlqXVsKV,iv:J5run3HY6sQLVb6ZWSy5CLzUzkZnZ60nmbRMbLr17ys=,tag:GnuddH+d2B+wB24l9IDf1Q==,type:comment]
accesslog:
  addInternals: ENC[AES256_GCM,data:RQf7Bw==,iv:2pblh7f4ymYjxQM/TrQDGTw0Shuvhv3vHjrzff7tP/c=,tag:xjpJ5h/iKbyp3Pye6gF9TQ==,type:bool]
  filePath: ENC[AES256_GCM,data:CzRLvXtGCMIjsPC3q6K14Q==,iv:JN7W9RUYO3jJ27mLSHY6+MDPHHbus8aIJHln8kHOMDI=,tag:z9ODeiIEPRoYTa5DzR9gvA==,type:str]
  bufferingSize: ENC[AES256_GCM,data:fF5+,iv:mwpcHFVecZSzLpGsV7n1I0U+3qwM7QXRDjY30Vxow/8=,tag:B+NSWCrAGncnauXgGWr1Bg==,type:int]
  fields:
    names:
      #ENC[AES256_GCM,data:rE9ZLcej5DAyEDBAEqHe8yMLmRSnOieb3TeczIatNlDxR7f6PNJw9mdRJcJMayfUcrk=,iv:YMP4+EaIw1HXTrbHsM0nFCU6ZTLOxhtOsFsR88/43hw=,tag:Rc8j9yRLQl3oq2x1V1flYA==,type:comment]
      StartUTC: ENC[AES256_GCM,data:F7F2PQ==,iv:8Gciv5VLLph/El6yiy8Dst17zTjmqdL0LSK5MTx2LZw=,tag:kXLFNSPcIRts7wdfXCjazw==,type:str]
  filters:
    statusCodes: ENC[AES256_GCM,data:0ypohO+gWQJy359KhwREGNTQq6U1ur4=,iv:fzHIz2Aik5HfrvuEwKahjeLf1zd4TopdlQCLlxejMTk=,tag:ZPy3aEYD+C2w2yTSuJp5rw==,type:str]
#ENC[AES256_GCM,data:x/E2ETB66QDsMpTO5srtt0vcRfySO10OgCuy9O4Yh6RCB+ikPF/FhlzvciiibkN6hmYLJSYc10SmjrdT8Xnf,iv:7s+fCWFxeGfKiJ+QGgusw0NP/IGTHSnbXsUAr5MLVVw=,tag:1N5y2C43H4M9ygrk3M9Hlg==,type:comment]
#ENC[AES256_GCM,data:OxXHO2OEy7VERiHD8eBcY8zuDYEoD4/kJ3A3p1rPJ2MKvK3wmOpMWaNRgLoUP6HdufN7pSgVZtw6LSPYF4ttcsunvzWFA1g0/ZTu32bxnvNFQFdn+lY=,iv:651XfnxAZ4OVf50oapT555BOG50I5rcpf0Bu3bgn0Ok=,tag:LreN/FxQ/jaFSCIjoW5hPA==,type:comment]
#ENC[AES256_GCM,data:q5bA8HQVtKvcFhWzzG396aP2qp9lYXOy+/vip8lZFaj7BKfa0id+uhdBPDHP5T1htGLE8h8QYAQUsYt4L8Y6,iv:rnVJkykpsbHqkgoEI8QK19F8tpEEYh8f6CbkF5oFBBg=,tag:nJ+F5K5FLEMa+mM2WiaQVA==,type:comment]
metrics:
  prometheus:
    buckets:
      - ENC[AES256_GCM,data:a5Q8,iv:IOvXf0+7UEdtWmPHFNHvn4NZ/heJmRDgPg9rMXze2m0=,tag:vfUeAQl7ZGLgbyQt9NIXKA==,type:float]
      - ENC[AES256_GCM,data:dp0C,iv:Ep1TDjD2pVUwdNxttQa58V+An3s14Eo53Gk6VE0YSXw=,tag:r6PCekSriFk8CjU5ZIGfNQ==,type:float]
      - ENC[AES256_GCM,data:AMG5,iv:TUsBgxAuCL2j25baYIS2R+SbQtJ3aQIjNm0BRMN5gNM=,tag:05i7OTexaocBAlGI45Kyaw==,type:float]
      - ENC[AES256_GCM,data:TQ==,iv:j4+Jg/AZgcqTk1jCL9xuIANERr0ERRUgFJz/RN/9Y5U=,tag:Ehx+Yj6CzneMrlCdhktz7A==,type:int]
    addEntryPointsLabels: ENC[AES256_GCM,data:2Efjaw==,iv:foV6YIC2TrlD1nWntbevsekhL3yY7m0jsnfsk3jM3+Q=,tag:STV5zruCS+TtE8F+F+DvYQ==,type:bool]
    addRoutersLabels: ENC[AES256_GCM,data:Jdj7Vg==,iv:fz5ktrxCxVbdRO7yz9cuxmYKVCNY0cqjgZuZ67axAmM=,tag:a9i2S2rqBgI8LmTBpus0Fg==,type:bool]
    addServicesLabels: ENC[AES256_GCM,data:JYrcMg==,iv:xpLAN56puLfFXsl6Jg49SWtDDz2xamdYK69bvGE5Y+c=,tag:ahOV/BAtGrN0uaXmuGIUTw==,type:bool]
#ENC[AES256_GCM,data:bhCh/kvRWok44a8TLQjQXt3f7w6wsjYgn/Nso2O6QKDX7JpAzfIcfHwsv0PMdzQghU7uP7SZivyZcL+h1qVl,iv:x+8YH6dztQwDb1xfav+4PzMZEt6pPoyOZP6c/XLLkGA=,tag:JM7/yeExtE9Tr9F5WcHUDQ==,type:comment]
#ENC[AES256_GCM,data:+W1YUfIqByqbedSXIcHULfZmwD+k+ZkOi+SjQi+Vtf94G7uHBv7Fb6KKp3WSDS2Rf36IM4w4EIyfg1ocBKydpB8BA1hGSDVRpDeMCfbc+0jQ1l4RTZ4uxx9RmYWBN/j2fbwpoAGwvMTPmxiNNdbqhJJuyw==,iv:NJyjkQXTABTXr7jUx51/o3xshKDYQ3GeNWrAx23XgeE=,tag:JQOzh15y6uGvf+gO1dNRfg==,type:comment]
#ENC[AES256_GCM,data:dzwT27p+0RpoCrZx71B89fdKW0O2068WbuaRImqYkokZzuAv8aCAJvSw5JU4tNJ/14tPsKL72KPVTOFQq6Ks,iv:NFN+zpb7iqIuVgd1pP3FCQnCUQndXHUT33ezon7W48U=,tag:035mZMtnY3Pk1xnroUSEhA==,type:comment]
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: ENC[AES256_GCM,data:aJOz1Ag3XOlSUqMhwVizoxpRep7o66f0ToEZy+ciYyqliIwN7/8Qd6l88/U8Cn5b1kL/RwpMqA==,iv:t/N7t/nJZyHC4AFYTuiRRZ2Z89zl4wQGflafS8LtcRg=,tag:dDjJ6urEGs11xlg7dy9OcA==,type:str]
      version: ENC[AES256_GCM,data:2S+TdmJg,iv:Hup7eYrcg4H0yVo+ZFQf5O1C9UhhoE3cIBn7l0ywYZ8=,tag:ksBygSdcOFZGSsmPIj77xw==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkFjWlNQcExySGtMR0V6
        QjY4TkVCSUVoZEdVOE4ra1V6OUNva084YWowClh3Lzk2OTRzOHB1VW8xWEovNURL
        S3hlaTVLQ3hCWG9kSStYZXNRdG81SGcKLS0tIHFsdEdIMU0wVGdmVkFBKyttQmt1
        ak9tWWcxQWxFWCtUQld0c2hGblhIb2cKLhlkk292133WZK4Pr5ZMrBTRKHzNeP/g
        8mBYZ/MkxkjftFRA0j06FeVLottC/CJ5OMCxMKNnBGnAKC0pPM6Ikw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T23:17:57Z"
  mac: ENC[AES256_GCM,data:ryFmqsRs4UpBEapVqhQA2l1li2DnTuNFz0zJadZK5iw7hp3fL60oEjOcrGo3L3wQovcqoMNrtdSBi6dcu6TKKSAk9vpaJ+gWHKm7BH7D4YJTCRb62ezABDFpuP6DVkwayHoIEl58HPYvj4JCbb+lyWT8brQdmWX7ueI7MuLoivM=,iv:j9rqtne+BUW24BB6zx4tQ0wmBkOFPXlylp0//c3a25Y=,tag:lJ5r1FAHGByLVkipyDQZew==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
