{
 "title": "Docker and System Monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\", instance=~\"$server\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (instance) (\n  (node_filesystem_size_bytes{instance=~\"$server\", host_type=\"lxc\", fstype=~\"xfs|ext4|zfs|overlay2\"} - node_filesystem_free_bytes{instance=~\"$server\", host_type=\"lxc\", fstype=~\"xfs|ext4|zfs|overlay2\"}) \n  / node_filesystem_size_bytes{instance=~\"$server\", host_type=\"lxc\", fstype=~\"xfs|ext4|zfs|overlay2\"}\n) \nor \nmin by (instance) (\n  (node_filesystem_size_bytes{instance=~\"$server\", host_type=\"vm\", fstype=~\"xfs|ext4\"} - node_filesystem_free_bytes{instance=~\"$server\", host_type=\"vm\", fstype=~\"xfs|ext4\"}) \n  / node_filesystem_size_bytes{instance=~\"$server\", host_type=\"vm\", fstype=~\"xfs|ext4\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (container_memory_usage_bytes{instance=~\"$server\", host_type=\"lxc\", id=\"/\"} / container_spec_memory_limit_bytes{instance=~\"$server\", host_type=\"lxc\", id=\"/\"}) * 100\n) \nor \n(\n  ((node_memory_MemTotal_bytes{instance=~\"$server\", host_type=\"vm\"} - node_memory_MemAvailable_bytes{instance=~\"$server\", host_type=\"vm\"}) / node_memory_MemTotal_bytes{instance=~\"$server\", host_type=\"vm\"}) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  node_load1{instance=~\"$server\", host_type=\"lxc\"} / on(instance) group_left() \n  count by (instance) (label_replace(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\", host_type=\"lxc\"}, \"instance\", \"$1\", \"instance\", \"([^:]+)(:.*)?\"))\n)\nor\n(\n  node_load1{instance=~\"$server\", host_type=\"vm\"} / on(instance) group_left() \n  count by (instance) (label_replace(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\", host_type=\"vm\"}, \"instance\", \"$1\", \"instance\", \"([^:]+)(:.*)?\"))\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_network_receive_bytes_total{ instance=~\"$server\", host_type=\"lxc\", id=\"/\"}[$interval]))\nor\nsum by (instance) (rate(container_network_receive_bytes_total{ instance=~\"$server\", host_type=\"vm\"}[$interval]))",
     "legendFormat": "RECEIVED ({{instance}})"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$server\", id=\"/\"}[$interval])) by (instance, id)",
     "legendFormat": "SENT ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{instance=~\"$server\", mode!=\"idle\"}[$interval])) \n  / \n  count by (instance) (node_cpu_seconds_total{instance=~\"$server\", mode=\"idle\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  node_load1{instance=~\"$server\", host_type=\"lxc\"} / on(instance) group_left() \n  count by (instance) (label_replace(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\", host_type=\"lxc\"}, \"instance\", \"$1\", \"instance\", \"([^:]+)(:.*)?\"))\n)\nor\n(\n  node_load1{instance=~\"$server\", host_type=\"vm\"} / on(instance) group_left() \n  count by (instance) (label_replace(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\", host_type=\"vm\"}, \"instance\", \"$1\", \"instance\", \"([^:]+)(:.*)?\"))\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_filesystem_size_bytes{instance=~\"$server\", host_type=\"lxc\", fstype=~\"ext4|xfs|zfs|overlay2\"} \n  - node_filesystem_free_bytes{instance=~\"$server\", host_type=\"lxc\", fstype=~\"ext4|xfs|zfs|overlay2\"}\n)\nor\n(\n  node_filesystem_size_bytes{instance=~\"$server\", host_type=\"vm\", fstype=~\"ext4|xfs\"} \n  - node_filesystem_free_bytes{instance=~\"$server\", host_type=\"vm\", fstype=~\"ext4|xfs\"}\n)",
     "legendFormat": "Used Disk Space ({{instance}})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{instance=~\"$server\",name=~\".+\"}) by (instance)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$server\"}[$interval])) by (instance, device)",
     "legendFormat": "Server: {{instance}}, OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$server\"}[$interval])) by (instance, device)",
     "legendFormat": "Server: {{instance}}, IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$server\", name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$server\", name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$server\", name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{instance=~\"$server\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$server\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"$server\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}