sudo_user: ENC[AES256_GCM,data:5eKurg==,iv:JIES8aY6F0H40+d9Q3FMcbO8lH/PeJm8zxvlp87Zgyw=,tag:mx4UvfJZuv+ZdTyJy/nFRw==,type:str]
ssh_private_key_file: ENC[AES256_GCM,data:K7zgNRBZqLhzQEywALnZJ9Xg2eUjRjmARpZL,iv:z9D4MDZWs9UKyStGfiV51o09mbaQZeFklEZCt/2QkKU=,tag:fN+HFVuFP4266AnjCgZeVQ==,type:str]
#ENC[AES256_GCM,data:hIKBytzYHIRsL9BQiMx1qLKFCPeCXbNIY/7XumIy4+PBCR1w+5cG8SqayKMrI6sM5M/bbmMr04zIAAuSL1wqPyg=,iv:QgDKSvaW12nKo2Vz23zpE67d2hwSIRN7zrLvutQWXsU=,tag:8iIbdW/QFzeLQsJlmpWewA==,type:comment]
run_host_ansible_bootstrap: ENC[AES256_GCM,data:aqTr6g==,iv:gqf0u/qAA93a2vZm47Y39w0dKGAqIM6b1H/FK9xkUzs=,tag:pge08IwHwefk45atigbMbg==,type:bool]
timezone: ENC[AES256_GCM,data:GOehHyON+9ACTvs0Zw==,iv:Rbc79pcqYMqFdOEx0Tuwycxvhnjr+OcQEevaLhveYK0=,tag:7uDjz1y+agSGLofiWhlkdg==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:REqgC63KPUszQdfk6H43BQ==,iv:ziosyMXctD0iFzVk0VO8vjJ29x7uqZyUegMCaJ1Pj0Q=,tag:gA+zgvLKSRFl9yTh1CkkEA==,type:str]
discord_webhook_url: ENC[AES256_GCM,data:LcJBNe4MhrGbaKsVhQEL1Ey9erBvgvHosdUaEZRaEx7GxjDqYQJFkhchpxSon2NP0haxELXVi20bJcC0MSNC9aRVAIEQGu2LnavP77lbdNAoGPL1GOYaFOIKCsZ8GN2iQ/ieJym9p6up+BAk0bKMYVZsuJp1VP2WGA==,iv:VVC3D+VuK6VB+k8UiV68lBb22PJ9hje7Pt3IMez9CC8=,tag:xPs1r4+YHjl4Pvn4ACBBWw==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUgvZFRpWDlpVzVuMTdZ
        OHNBV2ZKMWREZFNidFY4SzljYUhGZmlqd0JzCkUrQzdkOFpmR3MzTjFPZGlpemVq
        NUM4RXpDQmFya0FhaTdwMXh3eDM2QmMKLS0tIDFLQklBb1dwQUs0cmI2TXpVNDJL
        eFZpQWcyZFV2SXd0YUtQY001SE1RVkkKqQ2tqeKThvwtyFwb64/cKnLgwWy0iVeO
        pZrOPLit+kuTPbAu8AtaugGQSEAl11GQUYDhHa5h9g1/0mjoZ65Xew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-14T10:51:31Z"
  mac: ENC[AES256_GCM,data:IzAseZz1bZburczTtn/CaMwdfZ9pykUBAADQyHojZr8tY8Mj7oIjF18R7T9MA+B1NZwD9zYumQSPlbXgc7mER73VW+tHRTARCmm/7Y/FWDnQQass2aNkdg416CUstfP6JdeYhpXYy2+WNJCJ7jWTi2xoSlYw28WL0d4+p5HoWjg=,iv:2SaANvDd67wv/I1vliOpJa5CvrnALe2euUA5uAnbv7w=,tag:zISerW1H7pFfVYXO5vKYXg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
