sudo_user: ENC[AES256_GCM,data:oTwhYg==,iv:uk4Vmo+a6tJmcaNYzxKb0nkNcfMyss1auQGDxZfzHdg=,tag:Dehda1QTRIyIt1x1MhomlA==,type:str]
ssh_private_key_file: ENC[AES256_GCM,data:MBbOI052aloBhuhrdbiBiwZC+ks5lyUd88QO,iv:ZoCTbrMMj+IMAKYOfsrC9um3W1uqqb8mlCYdl5pivSI=,tag:b/pE0HXXajnyyCkQJ18BPg==,type:str]
#ENC[AES256_GCM,data:SslhCB9LbQ+keDT/B4JrcJbLU4eQK9A/KfuP6LNofwi1tgoIOLcsuC6a/2Khi+xAStGWPVMMLYCyeyzu6zY15Ew=,iv:lUAAi0qcHdrRmvD51mFKWfGVHj936JyMmL4vMEHNj6M=,tag:8KcIIztYhQxoPzkRsQHK1Q==,type:comment]
run_host_ansible_bootstrap: ENC[AES256_GCM,data:gsj54cE=,iv:S0tg7i/BOoAXGrCrDAlVQP7OcUn5aJmL0WhQ/gTj7lg=,tag:0zZcpOTuOVBvaRCnAdZBpA==,type:bool]
timezone: ENC[AES256_GCM,data:6n3o6mjHbkNfMy8f1A==,iv:Q4ZH+RVphHcZlzqxdWVRoSOARjEgyOI1dcs1mabgjco=,tag:u0G2i2UM9oC/tzlKjdGK1g==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:x4bo/PBpo4mIJM/waEYlfA==,iv:Ux/Lz3i3X0Eib1wmk6WFHMY4gVHQ0yKbvuzOS+pf8P8=,tag:kTh6OJlfwMlbMIfZmg56eg==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYXBONGVSc0tJUHFUQzdR
        bGdsb0hVcWZzOEd3SEx6d3k2NFQ0aXhQSVJNCm96S2t5NVlxclY3dGZ2Q01pU0lh
        RUMrK2JMU3Y3NDg4UXJkY3RuZTRwK3cKLS0tIDBFejVsRGFlcHRiTi8zTk0vL1py
        WnNoQzcwYmptdk9QNFg3UmQxWmlkWkkKAVC9vIK4Ty0dV+YYrSNwvXl8mJctHBw7
        6VkeFPPDH3JVgZpx+HugBrdeiekH2zZBEgbqwtGMsF1PdNMMZrvmjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-12T13:48:10Z"
  mac: ENC[AES256_GCM,data:Ne7Wr5aY2+P5lGKmSxt5MnqolI0gm3SUoIo7vzTmZREKobhr9rkMu74cG9QogS6ZcoEtAEuPi2EbndgWuvBig2U3GtNR/pjIYO/Tg2jDoJBoKQPO4UZhW8msjsop/cbsilElewqHaZV1g2XkqugYF/pXJu+utYmcmUdexkNaoKI=,iv:dbQdEICrh8+0C5umxdgfH5XVaxIqA7rQSGXf6Su66RI=,tag:CqpxPDG7/amvTYdf6W7Rqg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
