#ENC[AES256_GCM,data:dWOw/5VB7KZ3zejPESD1RWXyjIM=,iv:F9KEIjClv2/cMacHu7Dl6/5Te9xqxAom64RHLA61U2w=,tag:YS+vCuVyU69eSbflRDj/1g==,type:comment]
ansible_user: ENC[AES256_GCM,data:zGKCxC01sQ==,iv:sb6ZRlkG4FGCmrnujX0n3uh0ukbpyijYCU6a2HI4q3U=,tag:UOHOLO3zZTRpbj1YlfyOiw==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:+sGpGMVWcLKtzccKX80pHGSxfO0pFghETbnCJgQ=,iv:zKf+HgzeeFIzXcwjrDhgEaL0F2+Q2sa/O4apIjnIExE=,tag:j+KmiPVIDHyIaqVQqEr5lQ==,type:str]
ansible_become: ENC[AES256_GCM,data:36KQ,iv:OrdJqGbOt4CDdpXz9Q34UXE0TxkoFRZt+2zOpXLc1S8=,tag:/TOHN8Mb+XeT5d4Ky/pd3g==,type:str]
run_host_ansible_bootstrap: ENC[AES256_GCM,data:0Lh+jQ==,iv:I+6D2ZTQ6Nze+LG4Ton5FpoAdvSrdpT1gilTcp4ooRU=,tag:WspnTZqn0DV7SaE5robIug==,type:bool]
discord_webhook_url: ENC[AES256_GCM,data:JR7Wok7PPFP/2bguIhKg7lYLv9BTRmayKT3AOLBbpCcI+XJiasw6jLAZZccEzesUAmTmCL0+o0P5ay+SXpKc04vhTMzXmKQrQN2JX7710++Bn0Qw0SdX44XTIPXcu/tUICBmldQ00949ppk26HZUPRA2scIQ+YFpJQ==,iv:lkw0BEnlxLPSFibrEIwEXquNt3h/Ypl3KJ+o8qvMf2s=,tag:TGACM+D9ZqwvEXt7bHEHyw==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOFBEZTBGOE1iYTFKOGdR
        RXBMNEIyOWRLam1RSEQzMnRQTWZpQmpMTVhNCjRrZ0VVTEhHTTE5OGpSL0Z1Z0JE
        emVxc29YRWZjSjJhaDE2bTNuWnEwYnMKLS0tIDJzT2RmT2lvQVhoYXBVbG9raEo3
        NmZ1eUNnNGZVWnZzUkpHSTNlREdoeTQKSEMNPivDZFp4vHosR5B8YatTssHXU4yl
        a5kUtoAlmWTCFB8Ru3LbgDNYp/hUxckRmfmEHloBgpZIMAACXKMUBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-12T13:48:10Z"
  mac: ENC[AES256_GCM,data:LPeFlJa/zIlN8wl8wHNWJSweNyWp3NKvIbM1XPCSo9VRY4p9RhjKi18sDQXRjzfsBSJ+TisFl1TR877P26nBvOsTSwOCYMeWRTBdiOQfm/vwzx5zK5DSVmgxEwrlfr0VTFVYQXkPVsoE5XH+6omzt0NrXpQU4rbBSWw6F5rRd34=,iv:BPeifDnwvZxo63KphlMxCbT8i9W1WWvFA8v+c+GoqrE=,tag:GohNFZPGPW0fslELFDNULg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
