ansible_user: ENC[AES256_GCM,data:stY10SsixA==,iv:MIFAg/ujsCi7Uz9Wm2hLomDyHx+BLaukSu3k9oR8XFg=,tag:ySDI2ya6fIh76ewg3d1DNA==,type:str]
ansible_uid: ENC[AES256_GCM,data:1f1O+A==,iv:rG1Pug2kzte8R8Z1vQO/fJAwGsPJMkGnbpCkz2v3FCo=,tag:ge0y0jWTDj3ygpE2yVgStw==,type:int]
ansible_gid: ENC[AES256_GCM,data:09GWpg==,iv:D2r0YusJ5fl3Btl5eI3hjPYEETTq6n9ckd6WC3YGtTw=,tag:eKa5DSt0fYRGL+pjSHKaFw==,type:int]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:A+2kt9+wbHkkNN+Cnhe0n9QJHg/HOlZsWZkQv4I=,iv:GrMBTQeR9oWcDcAio5H8JhgQ3w/FJYrn1D/vxb9s5Ow=,tag:mFajlfbRUsCiV2/MIua+rg==,type:str]
ansible_become: ENC[AES256_GCM,data:NdC7,iv:Ills7WggVD1ZcYdpbr7Kv4DBSu9PEAvzGfP1WpjHdy4=,tag:27PD4CHkOjKlCM8c/O9HAg==,type:str]
run_host_ansible_bootstrap: ENC[AES256_GCM,data:jjtqaQ==,iv:GJLgm+NfWIlYvES2mNFhZgxVQ87eQqYgE23dm8tt+hM=,tag:OhiZ9MS7TuzeTynxPos+TQ==,type:bool]
discord_webhook_url: ENC[AES256_GCM,data:d/vlTXPnqbW27U0A9NPrha+DqZoDhhSwkmKSGkrTXDXd9JlE7iD4xWTIuAUQ1n1aYjFw9DWgfq2fZBn3B0+maWdTY778fMXNJxuSa2a3k6vAeWwv++CvDWiEckaJh3dGigZ5zBGVmYMSzGJmdzs4b2WJEvPC57fCgQ==,iv:nq77eVApoCT5kxq96uO9T8Z7fG7ozcgHihlAELOCvWE=,tag:3acZ5AWVUxJLYdKwcGzZHg==,type:str]
sops:
  age:
    - recipient: age1dlhdlc6uflznqd6y5lfq0urews04ut7rt9e2gxqh55kzks9yd5vsrsufgp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdWFpWGwzQ2JWK21nMG05
        Y3Y4eWducU10dzY1U3ZLSFhnbHF5WkFzSlhJCi9ZSW1mRmZJL1I3dlp3bEorVFUr
        WHA3VlZIUE8rR2JEZW1uZWxudkc5Wm8KLS0tIGhqNVNZUFdnWFdWRUwyaVJpb2Nh
        bng0bTZDM005OVNLc0h5YWQzalJRcmsKbg+hQq5gbRbC0FUn8A5+A8hCWebbbqX/
        eZGiL1mwi/lpB7ofegVvBTV6XtHziZTPxwq07t7F29SMSefzBXlrWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-03T22:35:27Z"
  mac: ENC[AES256_GCM,data:xow1WNp9B+HV7AsT64/FYBdnflDpwEBOFDj372/cK0fFYEyYopnoophE8cw21n34tAg1gaLQ/M7Ar9m651RQLi7tp4s778eDfuF1koe5Ni5tz6tzeeifjY1EFHk/G1qKwg1cONfv2OgAJEzWLdYGn58XsFqpmw693cCX1+85tC8=,iv:h2kHRdwwkJHGMI3OWunyy5KWfGosoHzr1rwRGLSnvRw=,tag:zwPN+R3DAlXgW6wv0g6vtA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
