---
services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    # profiles: ["core", "all"]
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - HTPASSWD_FILE=/run/secrets/basic_auth_credentials
      - DOMAIN=${FQDN}
      - DNS_ZONE=${DNS_ZONE:-${FQDN}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
      - ./logs:/logs:rw
    networks:
      - traefik
      - socket_proxy
    secrets:
      - cf_dns_api_token
      - basic_auth_credentials
    command:
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.websecure.http.tls.certresolver=${CERT_RESOLVER}
      - --entrypoints.websecure.http.tls.domains[0].main=${FQDN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${FQDN}
      # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=${CLOUDFLARE_IPS},${LOCAL_IPS}
    labels:
      - traefik.enable=true
      # Traefik Dashboard/API
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${FQDN}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.traefik.service=api@internal
