---
services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 465:465   # SMTP over SSL
      - 8120:8120 # Komodo Periphery TCP
      - 9001:9001 # Portainer Agent TCP
    profiles: ["prod", "dmz"]
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN_FILE=${CF_DNS_API_TOKEN_FILE:-/run/secrets/cf_dns_api_token}
      - HTPASSWD_FILE=${HTPASSWD_FILE:-/run/secrets/basic_auth_credentials}
      - DOMAIN=${FQDN}
      - DNS_ZONE=${DNS_ZONE:-${FQDN}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/etc/traefik/:ro
      - traefik-certs:/var/traefik/certs/:rw
      - traefik-logs:/logs:rw
    networks:
      - traefik
      - socket_proxy
    secrets:
      - basic_auth_credentials
      - cf_dns_api_token
      - crowdsec_lapi_key
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${FQDN}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.traefik.tls.domains[0].main=${FQDN}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${FQDN}
      - traefik.http.routers.traefik.middlewares=chain-authentik@file

volumes:
  traefik-certs:
    name: traefik-certs
    driver: local
  traefik-logs:
    name: traefik-logs
    driver: local
