{
 "title": "Traefik Official Docker Dashboard",
 "description": "Official dashboard for Standalone Traefik",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_open_connections, entrypoint)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[$interval])) by (env, entrypoint)",
     "legendFormat": "{{entrypoint}} ({{env}})"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (env, method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (env, method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (env, method)\n",
     "legendFormat": "{{method}} ({{env}})"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) by (env, method, code)",
     "legendFormat": "[{{env}}] {{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\n  avg by (service, instance, env, method, code) (\n    label_replace(\n      sum by (service, instance, env, method, code) (traefik_service_request_duration_seconds_sum{protocol=\"http\"})\n      / \n      sum by (service, instance, env, method, code) (traefik_service_request_duration_seconds_count{protocol=\"http\"}),\n      \"service\", \"$1\", \"service\", \"^([^@]+).*\"\n    )\n  )\n)",
     "legendFormat": "[{{env}}] {{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Most requested services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n  sum by (service, instance, env, method, code) (\n    label_replace(\n      rate(traefik_service_requests_total{service=~\"$service.*\", protocol=\"http\"}[$interval]),\n      \"service\", \"$1\", \"service\", \"^([^@]+).*\"\n    )\n  ) > 0\n)",
     "legendFormat": "[{{env}}] [{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services failing SLO of 1200ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (env, service)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"1.2\",service=~\"$service.*\"}[$interval])) / sum by (env, service) \n    (rate(traefik_service_request_duration_seconds_count{service=~\"$service.*\"}[$interval]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "[{{env}}] {{service}}"
      }
     ]
    },
    {
     "title": "Services failing SLO of 300ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (env, service)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",service=~\"$service.*\"}[$interval])) / sum by (env, service) \n    (rate(traefik_service_request_duration_seconds_count{service=~\"$service.*\"}[$interval]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "[{{env}}] {{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (service, instance, env, method, code) (\n    label_replace(\n      rate(traefik_service_requests_total{service=~\"$service.*\", code=~\"2..\", protocol=\"http\"}[$interval]),\n      \"service\", \"$1\", \"service\", \"^([^@]+).*\"\n    )\n  ) > 0\n)",
       "legendFormat": "[{{env}}] {{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "5xx over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (env, service,method,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",code=~\"5..\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "[{{env}}] {{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "Other codes over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (env, service,method,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",code!~\"2..|5..\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "[{{env}}] {{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "Requests Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (env, service,method) \n          (rate(traefik_service_requests_bytes_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "[{{env}}]  {{method}} on {{service}}"
      }
     ]
    },
    {
     "title": "Responses Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (service, instance, env, method, code) (\n    label_replace(\n      rate(traefik_service_responses_bytes_total{service=~\"$service.*\", protocol=\"http\"}[$interval]),\n      \"service\", \"$1\", \"service\", \"^([^@]+).*\"\n    )\n  ) > 0\n)",
       "legendFormat": "[{{env}}] {{method}} on {{service}}"
      }
     ]
    },
    {
     "title": "Connections per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(traefik_open_connections{entrypoint=~\"$entrypoint\"}) by (env, entrypoint)\n",
       "legendFormat": "{{entrypoint}} ({{env}})"
      }
     ]
    }
   ]
  }
 ]
}